display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        fid:
          label: 'ID файла'
        asset_type:
          label: Тип
        mime_type:
          label: Тип
        filesize:
          label: Размер
        source_type:
          label: Место
        operations:
          label: Операции
      pager:
        options:
          tags:
            next: 'Следующий ›'
            previous: '‹ Предыдущий'
            first: '« Первая'
            last: 'Последняя »'
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      filters:
        category:
          group_info:
            group_items:
              10:
                title: Другое
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: Категория
        mime_type:
          label: 'MIME тип'
        source_type:
          label: Место
        filesize_formatted:
          separator: ', '
        active_use_csv:
          separator: ', '
        used_in_csv:
          separator: ', '
