display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        source_entity_id:
          label: 'Идентификатор сущности'
        field_name:
          label: 'Название поля'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      arguments:
        asset_id:
          exception:
            title: Все
