display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        file_name:
          label: Название
        asset_type:
          label: Тип
        status_badge:
          label: Статус
        warnings:
          admin_label: Предупреждения
          label: Предупреждения
        operations:
          admin_label: Операции
          label: Операции
      pager:
        options:
          tags:
            next: 'Следующий ›'
            previous: '‹ Предыдущий'
            first: '« Первая'
            last: 'Последняя »'
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
          text_input_required: 'Выберите любой фильтр и нажмите Применить для просмотра результата'
          bef:
            general:
              secondary_label: 'Дополнительные настройки'
      filters:
        status:
          expose:
            label: Статус
          group_info:
            label: Статус
            group_items:
              1:
                title: Очередь
        asset_type:
          group_info:
            group_items:
              1:
                title: Документы
        archive_reason:
          group_info:
            group_items:
              1:
                title: Связь
              4:
                title: Другое
