display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        usage_field:
          label: Раздел
      pager:
        options:
          tags:
            next: 'Следующий ›'
            previous: '‹ Предыдущий'
            first: '« Первая'
            last: 'Последняя »'
      arguments:
        asset_id:
          exception:
            title: Все
