display:
  default:
    display_title: 'По умолчанию'
    display_options:
      fields:
        file_name:
          label: Название
        asset_type:
          label: Тип
      pager:
        options:
          tags:
            next: 'Следующий ›'
            previous: '‹ Предыдущий'
            first: '« Первая'
            last: 'Последняя »'
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
