title: 'Сообщить о дискриминации'
elements: |
  report_discrimination:
    '#title': 'Хотели бы вы подать жалобу на политику города или действия, предпринятые городской программой, сотрудником или подрядчиком, которые нарушают ваши права и дискриминируют вас?'
    '#options':
      'Yes': 'Да, я хотел бы сообщить о дискриминации'
      'No': 'Нет, но я хотел бы запросить размещение ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p>Пожалуйста, сделайте запрос через городскую службу <a href="/311/ada-request">размещения ADA</a> . Вы также можете позвонить нам по телефону <a href="tel:+1-503-823-4000">503-823-4000</a> или телетайпу через службу ретрансляции штата Орегон: <a href="tel:711">711</a> . Персонал готов помочь с понедельника по пятницу с 8:00 до 17:00.</p></div>'
  report_how_to_complete:
    '#title': 'Как бы вы хотели завершить свой запрос или отчет?'
    '#options':
      'Call us': 'Позвоните нам'
      'Continue online': 'Продолжить онлайн'
  confidentiality_waiver:
    '#title': 'Отказ от конфиденциальности'
    '#description': '<p>Политикой города является сохранение конфиденциальности информации, которую вы предоставляете в этой форме, в целях выполнения вашего запроса. Городские власти также попытаются сохранить конфиденциальность вашей информации в случае, если кто-то потребует, чтобы она была опубликована в качестве общедоступного документа в соответствии с <a href="/attorney/oregon-public-records-law" data-renderer-mark="true">Законом штата Орегон о государственных документах</a> . Если вы предпочитаете отказаться от этой конфиденциальности, выберите этот вариант ниже.</p>'
    '#options':
      'I do not waive confidentiality.': 'Я <em>не</em> отказываюсь от конфиденциальности.'
      'I choose to waive confidentiality.': 'Я отказываюсь от конфиденциальности.'
  report_who:
    '#title': 'От чьего имени вы обращаетесь с этим запросом или жалобой?*'
    '#options':
      Myself: 'От своего имени'
      'Someone else': 'От чьего-то имени'
      'Neither of these apply to me': 'Ни то, ни другое ко мне не относится'
  report_who_neither_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Next Steps</h2><p>Completing this form starts an investigatory and potentially legal process. It is intended to be used by individuals or on behalf of individuals that believe they have been discriminated against.</p><p>If you have a concern or are attempting to point out a condition in the city that may be intentionally or unintentionally leading to the discrimination of a protected class, please use our <a href="/help/contact-elected-official">Contact an elected official form.</a></p></div>'
  report_on_behalf_of_permission:
    '#title': 'Получили ли вы разрешение на подачу этой жалобы от соответствующих лиц?'
  report_on_behalf_of_name:
    '#title': 'Назовите имена лиц, подвергшихся дискриминации.'
  report_third_party_relationship:
    '#title': 'Как вы с ними связаны и почему вы подаете жалобу от третьего лица?'
  report_on_behalf_of_permission_text_stop:
    '#markup': '<h2>Следующие шаги</h2><p>Заполнение этой формы приведет к началу расследования и, возможно, юридического процесса. Форма предназначена для использования отдельными лицами или группами, которые считают, что подверглись прямой дискриминации.</p><p>Если у вас есть проблемы или вы хотите обратить внимание на ситуацию в городе, которая может намеренно или ненамеренно привести к дискриминации представителей защищенного статуса, воспользуйтесь нашей формой «Связаться с выборным должностным лицом».</p>'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p>Позвоните нам по номеру 311, <a href="tel:+15038234000">(503) 823-4000</a> или <a href="tel:711">711</a> для телетайпа через службу ретрансляции штата Орегон. Персонал доступен с понедельника по пятницу с 8:00 до 17:00, кроме государственных праздников.</p></div>'
  report_discrimination_basis:
    '#title': 'Я считаю, что дискриминация, с которой я столкнулась, была основана на...'
    '#description': '<p>(Проверить все, что относится)</p>'
  report_discrimination_date:
    '#title': 'Когда произошла дискриминация?'
  report_location:
    '#location_search__title': 'Где произошел инцидент? '
    '#place_name__title': 'Детали и название места'
    '#location_details__title': 'Укажите любую другую информацию, которая может помочь нам найти место, о котором вы сообщаете, в том числе, если у этого места есть название, например, если это общественное здание.'
  report_discrimination_bureau_office_etc:
    '#title': 'Укажите название городского бюро, офиса, сотрудника, мероприятия или программы, связанной с дискриминацией.'
  report_discrimination_description:
    '#title': 'Своими словами опишите предполагаемую дискриминацию.'
    '#description': '<p>Пожалуйста, объясните, что произошло; кто был вовлечен; какая политика, программа или деятельность были дискриминационными (если применимо); почему вы считаете, что это произошло, и как вы подверглись дискриминации. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.</p>'
  report_discrimination_witnesses:
    '#title': 'Были ли свидетели дискриминации?'
  report_discrimination_witnesses_contact_known:
    '#title': 'Знаете ли вы их имя и номер телефона или адрес электронной почты?'
    '#description': '<p>Со свидетелями будут связываться только в случае необходимости для расследования вашего заявления. В случае контакта свидетели могут выбрать, хотят ли они участвовать в процессе расследования.</p>'
  report_discrimination_witness_1_name:
    '#title': 'Имя первого свидетеля'
  report_discrimination_witness_1_phone:
    '#title': 'Телефон первого свидетеля'
  report_discrimination_witness_1_email:
    '#title': 'Электронная почта первого свидетеля'
  report_discrimination_add_witness:
    '#title': 'Добавить еще одного свидетеля?'
    '#options':
      'Add another witness': 'Добавить еще одного свидетеля'
  report_discrimination_witness_2_name:
    '#title': 'Имя второго свидетеля'
  report_discrimination_witness_2_phone:
    '#title': 'Телефон второго свидетеля'
  report_discrimination_witness_2_email:
    '#title': 'Электронная почта второго свидетеля'
  report_discrimination_file_upload:
    '#title': 'При необходимости приложите к жалобе любые фотографии или другие материалы.'
  report_discrimination_desired_outcome:
    '#title': 'Какое действие или решение вы хотели бы видеть принятым?'
  report_discrimination_filed_complaint_other:
    '#title': 'Подавали ли вы жалобу в какие-либо другие федеральные органы, органы штата или местные органы или в какой-либо федеральный суд или суд штата?'
    '#description': '<p>Вы имеете право обратиться в любое агентство или суд. Подача жалобы в другое учреждение или суд не мешает вам подать жалобу в город Портленд. В определенных ситуациях агентства будут координировать свои действия, чтобы обеспечить расследование жалобы соответствующим агентством или судом.</p>'
    '#options':
      'Yes': Да
      'No': Нет
      'Prefer not to answer': 'предпочитаю не отвечать'
  report_discrimination_filed_complaint_other_agency:
    '#title': 'Какой орган или суд?'
  report_agency_contact_markup:
    '#markup': '<p>Если вы подавали жалобу в другой орган или суд, укажите имя и номер телефона или электронной почты контактного лица или представителя, который принял жалобу, если у вас есть такие данные.</p>'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Агентство или контактное лицо в суде'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Контактный телефон агентства или суда'
  report_legal_representative_name:
    '#title': 'Укажите имя и контактную информацию своего юридического представителя, если таковой имеется.  '
  report_legal_representative_contact_number:
    '#title': 'Укажите имя и контактную информацию своего юридического представителя, если таковой имеется.  '
  contact_name:
    '#title': 'Ваше имя'
  contact_email:
    '#title': 'Эл. адрес'
    '#description': '<p>Мы будем использовать вашу электронную почту, чтобы подтвердить вашу заявку.</p>'
  contact_phone:
    '#title': Телефон
  contact_preferred_method:
    '#title': 'В случае необходимости вы бы предпочли, чтобы мы связались с вами по телефону или электронной почте?'
    '#options':
      Phone: Телефон
      Email: 'Эл. адрес'
  contact_interpreter:
    '#title': 'Вам нужен переводчик?'
    '#options':
      'No': Нет
      'Yes, VRI (Video Remote Interpretation)': 'Да, VRI (удаленный перевод видео)'
      'Yes, Oregon Relay Service': 'Да, служба ретрансляции штата Орегон'
      'Yes, language interpreter': 'Да, языковой переводчик'
  contact_language:
    '#title': 'На каком языке?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Заявитель Подтверждение</strong></p><p>Отправляя эту форму, я подтверждаю, что (1) я прочитал, понял и принимаю <a href="/code/23">условия процедур отслеживания и расследования жалоб на гражданские права</a> и (2) информация, которую я предоставил в этой форме, является достоверной, насколько мне известно.</p>'
  complainant_acknowledgement_agree:
    '#title': 'Я согласен'
  actions:
    '#title': 'Кнопки отправки'
    '#submit__label': 'Представлять на рассмотрение'
  report_ticket_id:
    '#title': 'Сообщить об идентификаторе заявки'
settings:
  confirmation_title: ''
  confirmation_message: ''
handlers:
  zendesk_new_ticket:
    label: 'Zendesk новый тикет'
    notes: 'Создает новую заявку на жалобу на дискриминацию и назначает ее группе 311: ADA и дискриминации.'
