elements: |
  report_confirm_non_emergency:
    '#title': 'Это экстренная, угрожающая жизни ситуация, когда есть пострадавшие или начался активный пожар?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Перестаньте заполнять эту форму и позвоните 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Пожалуйста, выберите ответ, чтобы продолжить.</strong></p>'
  markup:
    '#markup': '<p><em><strong>В периоды, сопряжённые с большим объёмом работы, правоохранительные органы не располагают ресурсами для реагирования на звонки, не связанные с экстренными ситуациями. Специалисты по расследованию пожаров будут расследовать все пожары, связанные с фейерверками, и нарушители будут привлечены к ответственности.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Пожалуйста, укажите, где вы находились, когда слышали фейерверк'
    '#location_address__description': 'Например, ваш домашний адрес'
    '#unit_number__title': 'Номер квартиры'
    '#location_city__title': 'Город'
    '#location_state__title': 'Штат'
    '#location_zip__title': 'Почтовый индекс'
  report_confirm_known_location:
    '#title': 'Вы знаете, откуда запускается фейерверк?'
  report_incident_location:
    '#title': 'Место происшествия'
  report_location:
    '#title': 'Место происшествия'
    '#location_search__title': 'Поиск места'
    '#location_search__description': 'Найдите на карте адрес, пересечение улиц, парк или общественный центр. Или используйте карту, чтобы нажать на точку.'
    '#location_details__title': 'Описание места'
    '#location_details__description': 'Укажите любые другие подробности, которые могут помочь нам определить место, о котором вы сообщаете.'
  report_date:
    '#title': 'Дата происшествия'
  report_time:
    '#title': 'Приблизительное время происшествия'
  report_incident_description:
    '#title': 'Приведите любое полезное описание происшествия'
    '#description': '<p>Например, цвет дома, владелец, связанные с происшествием автомобили, видео или аудиовизуальные материалы о происшествии, если они у вас есть. При необходимости с вами свяжутся, чтобы проинструктировать, как направить фотографии или видео.</p>'
  section_contact:
    '#title': 'Ваша контактная информация'
    '#description': '<p>Обратите внимание: В связи с ограниченными ресурсами НЕ ожидайте ответа на это сообщение.</p>'
  contact_name:
    '#title': 'Имя'
  contact_email:
    '#title': 'Электронная почта'
    '#description': '<p>Мы воспользуемся вашим адресом электронной почты, чтобы подтвердить подачу сообщения.</p>'
  contact_phone:
    '#title': 'Телефон'
  section_confidentiality:
    '#title': 'Конфиденциальность'
  confidentiality_waiver:
    '#title': 'Отказ от обеспечения конфиденциальности'
    '#description': '<p>Городское управление руководствуется правилом обеспечения конфиденциальности информации, указанной вами в данной форме, для выполнения вашей просьбы. Городское управление также попытается обеспечить конфиденциальность вашей информации, если кто-то попросит раскрыть её как документ публичного характера в соответствии с <a href="/attorney/oregon-public-records-law">Законом Орегона «О  документах публичного характера»</a>. Если вы предпочитаете отказаться от такого обеспечения конфиденциальности, пожалуйста, выберите соответствующий вариант ответа ниже.</p>'
    '#options':
      'I do not waive confidentiality': 'Я <em>не</em> отказываюсь от обеспечения конфиденциальности.'
      'I waive confidentiality': 'Я хочу отказаться от обеспечения конфиденциальности.'
settings:
  confirmation_title: 'Благодарим за подачу жалобы!'
  confirmation_message: '<p>Ваше сообщение (№ #[webform_submission:values:report_ticket_id]) получено.</p><p>В периоды, сопряжённые с большим объёмом работы, правоохранительные органы не располагают ресурсами для реагирования на звонки, не связанные с экстренными ситуациями. Несмотря на недостачу ресурсов для реагирования на большинство жалоб на фейерверки, мы собираем информацию для постоянно проводимой работы по обеспечению соблюдения запрета на фейерверки. &nbsp;НЕ ожидайте, что мы перезвоним вам по поводу этого сообщения.</p><p>Специалисты по расследованию пожаров будут расследовать все пожары, связанные с фейерверками, и нарушители будут привлечены к ответственности.</p><p>Если в результате ситуации, связанной с фейерверком, есть пострадавшие или начался пожар, позвоните 911.&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>Благодарим за подачу жалобы!</h2><p>Your report (#[webform_submission:values:report_ticket_id]) has been received.</p><p>During high volume times of the year law enforcement does not have resources to respond to all non-emergency calls. While resources are not available to respond to most complaints about fireworks, we are gathering information for ongoing efforts to achieve compliance with the Fireworks Ban. You should NOT expect a call back regarding this report.</p><p>Fire Investigators will be investigating all fires that have a connection to fireworks and violators will be held responsible.</p><p>If a fireworks situation involves someone being hurt or something is on fire, call 911.</p>'
