title: 'Запрос на размещение ADA'
elements: |
  request_how:
    '#title': 'Как бы вы хотели сделать свой запрос?'
    '#options':
      'I would like to call the City': 'Я хотел бы связаться с городской администрацией по телефону или через TTY.'
      'I will continue with the online form': 'Я продолжу онлайн-форму'
  markup_continue:
    '#markup': '<p class="mt-5"><strong>Пожалуйста, сделайте выбор, чтобы продолжить.</strong></p>'
  request_call_city_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p>Позвоните нам по телефону <a href="tel:311">311</a> , <a href="tel:+15038234000">(503) 823-4000</a> или <a href="tel:711">711</a> для телетайпа через службу ретрансляции штата Орегон. Персонал доступен с понедельника по пятницу с 8:00 до 17:00, кроме государственных праздников.</p></div>'
  request_who:
    '#title': 'От чьего имени вы подаете этот запрос или жалобу?'
    '#options':
      Myself: Сам
      'Someone else': 'Кто-то другой'
      'Neither of these apply to me': 'Ни одно из этого ко мне не относится.'
  request_who_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Информация</h2><p>Выбирая данный вариант, я подтверждаю, что имею инвалидность, подпадающую под действие Закона США об американцах с ограниченными возможностями (ADA), и что информация, предоставляемая мною в данной форме, является достоверной, насколько мне известно и насколько я в этом убежден.</p></div>'
  request_someone_else_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Информация</h2><p>Выбирая данный вариант, я подтверждаю, что лицо, от имени которого я подаю этот запрос или жалобу, имеет инвалидность, подпадающую под действие Закона США об американцах с ограниченными возможностями (Americans with Disabilities Act), и что информация, предоставляемая мною в данной форме, является достоверной, насколько мне известно и насколько я в этом убежден.</p></div>'
  request_who_neither_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Информация</h2><p>Данный вариант следует выбирать, если вы хотите сообщить о наблюдении, проблеме или опасении, которые, по вашему мнению, могут затронуть широкую общественность или представлять для нее угрозу — в особенности для людей с ограниченными возможностями. Пожалуйста, свяжитесь с нами по телефону <a href="tel:311">311</a> или по адресу <a href="311@portlandoregon.gov">311@portlandoregon.gov</a> для получения помощи.</p></div>'
  request_on_behalf_of_permission:
    '#title': 'Получили ли вы от них разрешение на подачу данной жалобы? Или же вас связывают правовые отношения, позволяющие вам подать жалобу от их имени?'
  request_on_behalf_of_name:
    '#title': 'Как их зовут?'
  request_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p>Прежде чем продолжить, убедитесь, что у вас есть разрешение этого человека на подачу жалобы или иное юридическое основание действовать от его имени. Если у вас нет такого разрешения или вы не уверены, остановите заполнение формы и свяжитесь с нами по телефону <a href="tel:311">311</a> или по адресу <a href="mailto:311@portlandoregon.gov">311@portlandoregon.gov</a> для получения помощи.</p></div>'
  container_confidentiality:
    '#title': Конфиденциальность
  confidentiality_waiver:
    '#title': 'Отказ от конфиденциальности'
    '#description': '<p>Политикой города является сохранение конфиденциальности информации, которую вы предоставляете в этой форме. Ваша информация будет храниться в тайне, если вы не установите флажок, подтверждающий, что вы хотите отказаться от конфиденциальности.</p>'
    '#options':
      'I do not waive confidentiality': 'Я <em>не</em> отказываюсь от конфиденциальности.'
      'I waive confidentiality': 'Я отказываюсь от конфиденциальности.'
  request_what:
    '#title': 'Я хотел бы попросить, чтобы город...'
    '#options':
      event_accommodations: 'Предоставление жилья для городского мероприятия, мероприятия или программы'
      parks_activity_registration: 'Обеспечить условия для регистрации и создания учетной записи для участия в мероприятиях Portland Parks & Recreation'
      city_materials: 'Предоставлять городские материалы в доступном для меня формате'
      app_accessibility: 'Исправить проблему с доступностью в приложении или на сайте города'
      remove_barrier: 'Убрать барьер или облегчить мне доступ к улице, тротуару, тропе, парку или другому пространству, принадлежащему городу (например, убрать препятствие на тротуаре, добавить пешеходные переходы или улучшить указатели)'
      change_policy: 'Измените или модифицируйте политику или процедуру (например, разрешите членам сообщества с ограниченными возможностями досрочно посещать мероприятие, разрешите сопровождающему лицу посещать занятия или мероприятия)'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите ваш запрос. Не включайте в него личную информацию или сведения о состоянии здоровья.'
  request_parks_assistance:
    '#title': 'Какая помощь вам нужна?'
    '#options':
      'Setting up my ActiveNet account (the system Portland Parks and Recreation uses for class/recreation registrations)': 'Настройка моего аккаунта ActiveNet (системы, которую Департамент парков и отдыха Портленда использует для регистрации на занятия и развлекательные мероприятия)'
      'Instructions and resources to help me get signed up for upcoming recreation activities': 'Инструкции и ресурсы, которые помогут мне записаться на предстоящие развлекательные мероприятия'
  container_materials:
    '#title': 'Запросить материалы'
  request_materials_type:
    '#title': 'Материалы, которые вы запрашиваете...'
    '#options':
      website: 'на сайте города?'
      event: 'для конкретного события или мероприятия?'
      printed: 'печатный документ недоступен в Интернете?'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите материалы.'
  request_materials_url:
    '#title': 'Каков веб-адрес (URL) страницы, на которой размещены материалы?'
  request_materials_description:
    '#title': 'Название и/или описание документа'
  page_you_last_viewed:
    '#title': 'Страница, которую вы просматривали последней'
  container_event:
    '#title': 'Детали события'
  request_event_name:
    '#title': 'Название мероприятия, события или программы'
  request_event_date:
    '#title': 'Дата события'
  request_event_location:
    '#title': 'Место проведения'
  request_event_bureau_sponsor:
    '#title': 'Организатор мероприятия'
    '#description': '<p>Пожалуйста, укажите городское бюро, офис, программу, проект или выборное должностное лицо, которое проводит мероприятие, если вы знаете.</p>'
  request_event_url:
    '#title': 'URL-адрес сведений о событии'
    '#description': '<p>Скопируйте и вставьте URL-адрес веб-сайта мероприятия, программы или материала, если он известен.</p>'
  container_event_accommodations:
    '#title': 'Размещение на мероприятиях'
  request_event_accommodations_type:
    '#title': 'Какой тип размещения вы запрашиваете?'
    '#description': '<p>Проверить все, что относится.</p>'
    '#options':
      accessible_parking: 'Доступная парковка'
      accessible_entrance: 'Доступный вход на мероприятие и маршруты к туалетам'
      communication_aids: 'Коммуникационные средства'
      accessible_materials: 'Материалы в доступном формате'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите ваш запрос. Не включайте в него личную информацию или сведения о состоянии здоровья.'
  request_event_communiation_aids_type:
    '#title': 'Какой тип средств связи вы бы предпочли?'
    '#options':
      captioning: Субтитры
      listening_device: 'Вспомогательное прослушивающее устройство'
      interpretation_asl: 'Интерпретация в ASL'
      interpretation_other: 'Интерпретация на другом жестовом или тактильном языке'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите ваш запрос. Не включайте в него личную информацию или сведения о состоянии здоровья.'
  request_event_materials_format:
    '#title': 'Какой формат материалов мероприятия вы бы предпочли?'
    '#options':
      accessble_word_doc: 'Доступный электронный документ (Microsoft Word)'
      accessible_pdf: 'Доступный электронный документ (PDF)'
      large_print: 'Бумага с крупным шрифтом'
      braille: 'шрифт Брайля'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите ваш запрос. Не включайте в него личную информацию или сведения о состоянии здоровья.'
  container_remove_barrier:
    '#title': 'Удалить барьер'
  request_barrier_type:
    '#title': 'О какой проблеме вы сообщаете? Как мы можем облегчить вам доступ?'
    '#options':
      barrier: 'Барьер - есть барьер, препятствие или что-то на пути, препятствующее доступу.'
      parking: 'Парковка - Нет доступной парковки или есть проблема с существующими местами'
      signage: 'Вывески - Знаки отсутствуют или знаки нечеткие'
    '#other__option_label': 'Что-то другое...'
    '#other__description': 'Пожалуйста, опишите.'
  report_location:
    '#title': 'Расположение барьера или проблемы'
    '#location_search__title': 'Поиск по местоположению'
    '#location_map__title': 'Карта местности'
    '#suggestions_modal__title': Предложения
    '#status_modal__title': 'Индикатор состояния'
    '#location_address__title': 'Адрес или перекресток'
    '#location_lat__title': Широта
    '#location_lon__title': Долгота
    '#place_name__title': 'Укажите имя'
    '#location_details__title': 'Детали местоположения'
    '#location_asset_id__title': 'Идентификатор объекта'
  report_barrier_description:
    '#title': 'Описание проблемы'
    '#description': '<p>Пожалуйста, подробно опишите проблему. Как мы можем упростить доступ к вашему городу? Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.</p>'
  container_change_policy:
    '#title': 'Изменить политику'
  report_policy_request:
    '#title': 'Какова ваша просьба?'
    '#description': '<p>Пожалуйста, опишите изменение политики или процедуры, которое вы запрашиваете. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.</p>'
  section_contact:
    '#title': Контакты
  contact_name:
    '#title': 'Ваше имя'
  contact_email:
    '#title': 'Ваш адрес электронной почты'
    '#description': '<p>Мы будем использовать вашу электронную почту, чтобы ответить на ваш отзыв или запрос.</p>'
  contact_phone:
    '#title': Телефон
  contact_phone_assistance_type:
    '#title': 'Если вам нужна помощь по телефону, выберите один из вариантов'
    '#options':
      vri: ВРИ
      relay: 'Служба ретрансляции штата Орегон (TTY)'
      interpreter: 'Устный переводчик'
      none: 'Ни один из вышеперечисленных'
  support_agent_use_only:
    '#title__title': ''
  report_ticket_id:
    '#title': 'Сообщить об идентификаторе заявки'
  computed_location_address:
    '#title': 'Расчетный адрес местоположения'
  computed_location_latlon:
    '#title': 'Вычисленное местоположение Латлон'
  actions:
    '#title': 'Кнопки отправки'
    '#submit__label': 'Представлять на рассмотрение'
settings:
  confirmation_title: 'Спасибо за отправку вашего запроса!'
  confirmation_message: '<p>Ваш запрос получен, с вами свяжутся в течение 48 часов.</p>'
handlers:
  zendesk_new_ticket:
    label: 'Zendesk новый тикет'
    notes: 'Создает новый билет запроса на размещение ADA и назначает его группе 311.'
