label: Пол
options: |-
  'Gender expansive (e.g., non-binary, agender, gender fluid, genderqueer)': 'Gender expansive (e.g., non-binary, agender, gender fluid, genderqueer)'
  Man: Man
  Transgender: Transgender
  'Trans man': 'Trans man'
  'Trans woman': 'Trans woman'
  'Two Spirit': 'Two Spirit'
  Woman: Woman
  'I am undecided and/or questioning': 'I am undecided and/or questioning'