display:
  default:
    display_title: Базово
    display_options:
      fields:
        usage_entity_type:
          label: 'Тип елементу'
        usage_field:
          label: Розділ
      pager:
        options:
          tags:
            next: 'Наступна ›'
            previous: '‹ Попередня'
            first: '« Перша'
            last: 'Остання »'
      arguments:
        asset_id:
          exception:
            title: Все
