display:
  default:
    display_title: Базово
    display_options:
      fields:
        file_name:
          label: "Назва (ім'я)"
        asset_type:
          label: Тип
      pager:
        options:
          tags:
            next: 'Наступна ›'
            previous: '‹ Попередня'
            first: '« Перша'
            last: 'Остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
