display:
  default:
    display_title: Базово
    display_options:
      fields:
        source_entity_type:
          label: 'Тип елементу'
        source_entity_id:
          label: 'ID сутності'
        field_name:
          label: "Ім'я поля"
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      arguments:
        asset_id:
          exception:
            title: Все
