display:
  default:
    display_title: Базово
    display_options:
      fields:
        archive_path:
          label: 'URL файла'
        file_name:
          label: "Назва (ім'я)"
        asset_type:
          label: Тип
        status_badge:
          label: Стан
        warnings:
          admin_label: Попередження
          label: Попередження
        operations:
          admin_label: Операції
          label: Операції
      pager:
        options:
          tags:
            next: 'Наступна ›'
            previous: '‹ Попередня'
            first: '« Перша'
            last: 'Остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
          text_input_required: 'Щоб побачити результат, виберіть довільний фільтр і натисніть "Застосувати"'
          bef:
            general:
              secondary_label: 'Розширені параметри'
      filters:
        status:
          expose:
            label: Стан
          group_info:
            label: Стан
            group_items:
              1:
                title: 'В черзі'
        archive_reason:
          group_info:
            group_items:
              1:
                title: Посилання
              4:
                title: Інше
