display:
  default:
    display_title: Базово
    display_options:
      fields:
        fid:
          label: 'ID файла'
        asset_type:
          label: Тип
        file_path:
          label: 'URL файла'
        mime_type:
          label: Тип
        filesize:
          label: Розмір
        source_type:
          label: 'Місце розташування'
        operations:
          label: Операції
      pager:
        options:
          tags:
            next: 'Наступна ›'
            previous: '‹ Попередня'
            first: '« Перша'
            last: 'Остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      filters:
        category:
          group_info:
            group_items:
              10:
                title: Інше
  data_export_csv_inventory:
    display_options:
      fields:
        file_path:
          label: 'URL файла'
        category:
          label: Категорія
        mime_type:
          label: 'Тип MIME'
        source_type:
          label: 'Місце розташування'
        filesize_formatted:
          separator: ', '
        active_use_csv:
          separator: ', '
        used_in_csv:
          separator: ', '
