elements: |
  report_confirm_non_emergency:
    '#title': 'Чи ця подія є надзвичайною, що загрожує життю, коли хтось постраждав або виникла пожежа?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Будь ласка, припиніть заповнювати цю форму та зателефонуйте за номером 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Будь ласка, оберіть відповідь, щоб продовжити.</strong></p>'
  markup:
    '#markup': '<p><em><strong>У періоди найбільшого навантаження протягом року правоохоронні органи не мають достатніх ресурсів для реагування на всі дзвінки, що не пов’язані з надзвичайними подіями. Фахівці з розслідування причин пожеж розслідуватимуть усі пожежі, пов’язані з використанням феєрверків, а винних осіб буде притягнуто до відповідальності.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Будь ласка, вкажіть своє місцезнаходження на момент, коли ви чули феєрверки'
    '#location_address__description': 'Наприклад, адресу вашого проживання'
    '#unit_number__title': 'Номер квартири'
    '#location_city__title': 'Місто'
    '#location_state__title': 'Штат'
    '#location_zip__title': 'Поштовий індекс'
  report_confirm_known_location:
    '#title': 'Чи знаєте ви місце, звідки запускали феєрверки?'
  report_incident_location:
    '#title': 'Місце події'
  report_location:
    '#title': 'Місце події'
    '#location_search__title': 'Пошук місця'
    '#location_search__description': 'Знайдіть на карті адресу, перехрестя, парк або громадський центр. Або натисніть на потрібне місце на карті.'
    '#location_details__title': 'Відомості про місце'
    '#location_details__description': 'Будь ласка, надайте будь-які додаткові дані, які можуть допомогти нам визначити місце, про яке ви повідомляєте.'
  report_date:
    '#title': 'Дата події'
  report_time:
    '#title': 'Орієнтовний час події'
  report_incident_description:
    '#title': 'Надайте будь-який корисний опис.'
    '#description': '<p>Наприклад: колір будинку, інформацію про власника, пов’язані з подією транспортні засоби, а також чи маєте ви відеозаписи або інші матеріали, що стосуються події. За потреби з вами зв’яжуться та нададуть інструкції щодо  надсилання фотографій або відеозаписів.</p>'
  section_contact:
    '#title': 'Ваша контактна інформація'
    '#description': '<p>Зверніть увагу: через обмежені ресурси НЕ слід очікувати відповіді на це повідомлення.</p>'
  contact_name:
    '#title': 'Ім’я та прізвище'
  contact_email:
    '#title': 'Електронна пошта'
    '#description': '<p>Ми використаємо вашу електронну адресу, щоб підтвердити отримання вашого повідомлення.</p>'
  contact_phone:
    '#title': 'Номер телефону'
  section_confidentiality:
    '#title': 'Конфіденційність'
  confidentiality_waiver:
    '#title': 'Відмова від конфіденційності'
    '#description': '<p>Політика міської адміністрації Портленду передбачає збереження конфіденційності інформації, яку ви надаєте в цій формі, з метою виконання вашого запиту. Міська адміністрація Портленду також намагатиметься зберегти конфіденційність вашої інформації, якщо хтось подасть запит на її розкриття як публічного документа відповідно до <a href="/attorney/oregon-public-records-law">«Закону штату Орегон про публічні документи» (Oregon Public Records Law)</a>. Якщо ви бажаєте відмовитися від цієї конфіденційності, виберіть відповідний варіант нижче.</p>'
    '#options':
      'I do not waive confidentiality': 'Я <em>не</em> відмовляюся від конфіденційності.'
      'I waive confidentiality': 'Я відмовляюся від конфіденційності.'
settings:
  confirmation_title: 'Дякуємо за подання скарги!'
  confirmation_message: '<p>Ваше повідомлення (№ [webform_submission:values:report_ticket_id]) отримано.</p><p>У періоди найбільшого навантаження протягом року правоохоронні органи не мають достатніх ресурсів для реагування на всі дзвінки, що не пов’язані з надзвичайними подіями. Хоча наразі немає можливості реагувати на більшість скарг щодо використання феєрверків, ми збираємо інформацію для подальшої роботи щодо забезпечення дотримання заборони на використання феєрверків. НE очікуйте, що вам телефонуватимуть у зв’язку з цим повідомленням.</p><p>Фахівці з розслідування причин пожеж розслідуватимуть усі пожежі, пов’язані з використанням феєрверків, а винних осіб буде притягнуто до відповідальності.</p><p>Якщо внаслідок використання феєрверків хтось постраждав або виникла пожежа, телефонуйте 911.&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>Дякуємо за подання скарги!</h2><p>Ваше повідомлення (№ [webform_submission:values:report_ticket_id]) отримано.</p><p>У періоди найбільшого навантаження протягом року правоохоронні органи не мають достатніх ресурсів для реагування на всі дзвінки, що не пов’язані з надзвичайними подіями. Хоча наразі немає можливості реагувати на більшість скарг щодо використання феєрверків, ми збираємо інформацію для подальшої роботи щодо забезпечення дотримання заборони на використання феєрверків. НE очікуйте, що вам телефонуватимуть у зв’язку з цим повідомленням.</p><p>Фахівці з розслідування причин пожеж розслідуватимуть усі пожежі, пов’язані з використанням феєрверків, а винних осіб буде притягнуто до відповідальності.</p><p>Якщо внаслідок використання феєрверків хтось постраждав або виникла пожежа, телефонуйте 911.&nbsp;</p>'
