<?php

/*
 * Implemenets hook_theme()
 */
function portland_geofield_theme() {
  return [
    'portland_geofield_widget' => [
      'variables' => [
        'mapid' => NULL,
        'width' => '100%',
        'height' => '40vh',
      ],
    ],
    'portland_geofield_formatter' => [
      'variables' => [
        'mapid' => NULL,
        'width' => '100%',
        'height' => '40vh',
      ],
    ]
  ];
}
