<?php

/**
 * Implements hook_install().
 */
function api_tests_install() {
  $config = \Drupal::configFactory()->getEditable('lightning_api.settings');
  \Drupal::state()->set('api_tests', $config->get());
  $config->set('entity_json', TRUE)->save();
}

/**
 * Implements hook_uninstall().
 */
function api_tests_uninstall() {
  $state = \Drupal::state();

  \Drupal::configFactory()->getEditable('lightning_api.settings')
    ->setData($state->get('api_tests'))
    ->save();

  $state->delete('api_tests');
}
