#! /bin/bash

set -e
TERMINUS_HIDE_GIT_MODE_WARNING=1

# store original mailer value and turn off mailer
original_mailer=$(terminus drush portlandor.$1 -- config:get mailsystem.settings defaults.sender)
terminus drush portlandor.$1 -- config:set mailsystem.settings defaults.sender 'test_mail_collector'

# create taxonomy terms
terminus drush portlandor.$1 -- cim -y && terminus drush portlandor.$1 -- portland:create_group_types

# migrate groups
terminus drush portlandor.$1 -- portland:list_group_by_type advisory_group > ids_advisory_group.log
for word in $(cat ids_advisory_group.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type program > ids_program.log
for word in $(cat ids_program.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type project > ids_project.log
for word in $(cat ids_project.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type bureau_office > ids_bureau_office.log
for word in $(cat ids_bureau_office.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done

# Delete groups:
# time terminus drush portlandor.$1 -- portland:delete_groups advisory_group
# time terminus drush portlandor.$1 -- portland:delete_groups project
# time terminus drush portlandor.$1 -- portland:delete_groups program
# time terminus drush portlandor.$1 -- portland:delete_groups bureau_office

# re-index
terminus drush portlandor.$1 -- sapi-r
terminus drush portlandor.$1 -- sapi-i

# retore mailer
terminus drush portlandor.$1 -- config:set mailsystem.settings defaults.sender $original_mailer
