#! /bin/bash

# Exit on error
set -e
# Turn off warning that the site is in GIT mode
export TERMINUS_HIDE_GIT_MODE_WARNING=1

# Turn off email notification on Live
if [[ $1 == "live" ]]
then
  terminus drush portlandor.$1 -- config:set mailsystem.settings defaults.sender 'test_mail_collector' -y
fi

# create taxonomy terms
terminus drush portlandor.$1 -- cr
terminus drush portlandor.$1 -- cim -y && terminus drush portlandor.$1 -- portland:create_group_types

# migrate groups
terminus drush portlandor.$1 -- portland:list_group_by_type advisory_group > ids_advisory_group.log
for word in $(cat ids_advisory_group.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type program > ids_program.log
for word in $(cat ids_program.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type project > ids_project.log
for word in $(cat ids_project.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done
terminus drush portlandor.$1 -- portland:list_group_by_type bureau_office > ids_bureau_office.log
for word in $(cat ids_bureau_office.log | grep -v "^$"); do time terminus drush portlandor.$1 -- portland:migrate_group $word; done

# Delete groups:
# time terminus drush portlandor.$1 -- portland:delete_groups advisory_group
# time terminus drush portlandor.$1 -- portland:delete_groups project
# time terminus drush portlandor.$1 -- portland:delete_groups program
# time terminus drush portlandor.$1 -- portland:delete_groups bureau_office

# re-index
terminus drush portlandor.$1 -- sapi-r
terminus drush portlandor.$1 -- sapi-i

# retore mailer on Live
if [[ $1 == "live" ]]
then
  terminus drush portlandor.$1 -- config:set mailsystem.settings defaults.sender 'sendgrid_integration' -y
fi