<?php

/**
 * Implements hook_form_alter().
 */
function portland_revision_helper_form_alter(&$form, $form_state, $form_id)
{
  if ($form_id == "node_city_service_edit_form") {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        array_unshift($form['actions'][$action]['#submit'], 'portland_revision_helper_need_revision_check');
      }
    }
  }

  
  // $test = $form;

  // $test2 = $form_state;

  // $test3 = $form_id;

  // $test4 = 'stop';
}

