display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
          tags:
            previous: ‹‹
            next: ››
      fields:
        id:
          label: ID
          separator: ', '
        drupal_entity__target_id:
          label: Entitate
          separator: ', '
        salesforce_id_1:
          separator: ', '
        salesforce_mapping:
          label: Mapare
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: 'Legături de operare'
  page_1:
    display_title: Pagina
