display:
  default:
    display_title: Implicit
    display_options:
      fields:
        fid:
          label: 'ID-ul fișierului'
        asset_type:
          label: Tip
        mime_type:
          label: Tip
        filesize:
          label: Mărime
        source_type:
          label: Locația
        operations:
          label: Operațiuni
      pager:
        options:
          tags:
            next: 'Următor ›'
            previous: '‹ Anterior'
            first: '« Primul'
            last: 'Ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      filters:
        category:
          group_info:
            group_items:
              10:
                title: Altele
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: Categorie
        source_type:
          label: Locația
        filesize_formatted:
          separator: ', '
        active_use_csv:
          separator: ', '
        used_in_csv:
          separator: ', '
