display:
  default:
    display_title: Implicit
    display_options:
      pager:
        options:
          tags:
            next: 'Următor ›'
            previous: '‹ Anterior'
            first: '« Primul'
            last: 'Ultimul »'
      arguments:
        asset_id:
          exception:
            title: Toate
