display:
  default:
    display_title: Implicit
    display_options:
      fields:
        file_name:
          label: Nume
        asset_type:
          label: Tip
        status_badge:
          label: Stare
        warnings:
          admin_label: Avertizări
          label: Avertizări
        operations:
          admin_label: Operațiuni
          label: Operațiuni
      pager:
        options:
          tags:
            next: 'Următor ›'
            previous: '‹ Anterior'
            first: '« Primul'
            last: 'Ultimul »'
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
          text_input_required: 'Selectați orice filtru și faceți clic pe Aplică pentru a vedea rezultatele'
          bef:
            general:
              secondary_label: 'Opțiuni avansate'
      filters:
        status:
          expose:
            label: Stare
          group_info:
            label: Stare
            group_items:
              1:
                title: 'Pus în coada de așteptare'
        archive_reason:
          group_info:
            group_items:
              1:
                title: Referință
              4:
                title: Altele
