display:
  default:
    display_title: Implicit
    display_options:
      fields:
        source_entity_id:
          label: 'ID-ul entității'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      arguments:
        asset_id:
          exception:
            title: Toate
