elements: |
  report_confirm_non_emergency:
    '#title': 'Este vorba de o situație urgentă, care pune viața în pericol, în urma căreia o persoană este vătămată sau s-a produs un incendiu?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Vă rugăm să vă opriți din completarea acestui formular și să sunați la 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Selectați o opțiune pentru a continua.</strong></p>'
  markup:
    '#markup': '<p><em><strong>În perioadele în care primim un volum mare de reclamații, autoritățile de aplicare a legii nu dispun de resursele necesare pentru a răspunde la toate apelurile care nu constituie urgențe. Anchetatorii specializați în incendii vor investiga toate incendiile care au legătură cu articolele pirotehnice de divertisment, iar contravenienții vor fi trași la răspundere.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Vă rugăm să ne comunicați locația dvs. atunci când sesizați folosirea articolelor pirotehnice de divertisment'
    '#location_address__description': 'De exemplu, adresa de domiciliu'
    '#unit_number__title': 'Numărul apartamentului'
    '#location_city__title': 'Orașul'
    '#location_state__title': 'Statul'
    '#location_zip__title': 'Codul poștal'
  report_confirm_known_location:
    '#title': 'Știți de unde au fost lansate articolele pirotehnice de divertisment?'
  report_incident_location:
    '#title': 'Locul incidentului'
  report_location:
    '#title': 'Locul incidentului'
    '#location_search__title': 'Căutarea locului'
    '#location_search__description': 'Căutați pe hartă o adresă, intersecții, un parc sau un centru comunitar. Sau folosiți harta pentru a selecta o locație.'
    '#location_details__title': 'Detaliile locului'
    '#location_details__description': 'Furnizați orice detalii care ne-ar putea ajuta să găsim locul pe care îl sesizați.'
  report_date:
    '#title': 'Data incidentului'
  report_time:
    '#title': 'Ora aproximativă a incidentului'
  report_incident_description:
    '#title': 'Furnizați o descriere utilă a incidentului'
    '#description': '<p>De exemplu: culoarea casei, proprietarul, vehiculele asociate, dacă aveți înregistrări video sau fișiere multimedia asociate incidentului. Dacă este necesar, cineva vă va contacta și vă va da instrucțiuni pentru a trimite fotografiile sau înregistrările video.</p>'
  section_contact:
    '#title': 'Informațiile dvs. de contact'
    '#description': '<p>Rețineți: Din cauza resurselor limitate, NU trebuie să vă așteptați la un răspuns la această sesizare.</p>'
  contact_name:
    '#title': 'Nume'
  contact_email:
    '#title': 'E-mail'
    '#description': '<p>Vom folosi adresa dvs. e-mail pentru a vă confirma trimiterea sesizării.</p>'
  contact_phone:
    '#title': 'Telefon'
  section_confidentiality:
    '#title': 'Confidențialitate'
  confidentiality_waiver:
    '#title': 'Renunțare la confidențialitate'
    '#description': '<p>Politica orașului Portland este de a păstra confidențialitatea informațiilor pe care le furnizați în acest formular, în scopul îndeplinirii solicitării dvs. Orașul Portland va încerca, de asemenea, să păstreze confidențialitatea informațiilor în cazul în care cineva solicită divulgarea acestora ca documente publice conform <a href="/attorney/oregon-public-records-law">legii privind documentele publice din Statul Oregon</a>. Dacă preferați să renunțați la confidențialitate, vă rugăm să selectați opțiunea de mai jos.</p>'
    '#options':
      'I do not waive confidentiality': '<em>Nu</em> renunț la confidențialitate.'
      'I waive confidentiality': 'Optez să renunț la confidențialitate.'
settings:
  confirmation_title: 'Vă mulțumim pentru depunerea reclamației!'
  confirmation_message: '<p>Am primit sesizarea dvs. (nr. [webform_submission:values:report_ticket_id]).</p><p>În perioadele în care primim un volum mare de reclamații, autoritățile nu au resursele necesare pentru a răspunde la toate apelurile care nu constituie urgențe. Deși nu sunt disponibile resurse pentru a răspunde la majoritatea reclamațiilor privind articolele pirotehnice de divertisment, colectăm informații în cadrul &nbsp;eforturilor continue de asigurare a conformității cu interdicția privind articolele pirotehnice de divertisment. NU trebuie să vă așteptați la un răspuns telefonic cu privire la această sesizare.</p><p>Anchetatorii specializați în incendii vor investiga toate incendiile care au legătură cu articolele pirotehnice de divertisment, iar contravenienții vor fi trași la răspundere.</p><p>Dacă o situație asociată cu articolele pirotehnice de divertisment implică vătămarea unei persoane sau dacă se produce un incendiu, sunați la 911.&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>Vă mulțumim pentru depunerea reclamației!</h2><p>Am primit sesizarea dvs. (nr. [webform_submission:values:report_ticket_id]).</p><p>În perioadele în care primim un volum mare de reclamații, autoritățile nu au resursele necesare pentru a răspunde la toate apelurile care nu constituie urgențe. Deși nu sunt disponibile resurse pentru a răspunde la majoritatea reclamațiilor privind articolele pirotehnice de divertisment, colectăm informații în cadrul &nbsp;eforturilor continue de asigurare a conformității cu interdicția privind articolele pirotehnice de divertisment. NU trebuie să vă așteptați la un răspuns telefonic cu privire la această sesizare.</p><p>Anchetatorii specializați în incendii vor investiga toate incendiile care au legătură cu articolele pirotehnice de divertisment, iar contravenienții vor fi trași la răspundere.</p><p>Dacă o situație asociată cu articolele pirotehnice de divertisment implică vătămarea unei persoane sau dacă se produce un incendiu, sunați la 911.&nbsp;</p>'
