<?php

use Drupal\webform\Utility\WebformElementHelper;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter 
 */
function portland_webform_form_alter(&$form, &$form_state, $form_id) {
  // if elements array exists, this may be a webform. flatten the elements array and look for
  // the location picker field. if it exists, attach the library.
  $library_attached = false;
  $form['#attached']['library'][] = 'portland_webform/portland_webform';
  $form['#attached']['drupalSettings']['portlandmaps_api_key'] = \Drupal::service('key.repository')->getKey('portlandmaps_api')->getKeyValue();
  $library_attached = true;
}

/**
 * Implements hook_webform_element_alter().
 *
 * @param array              $element
 * @param FormStateInterface $form_state
 * @param array              $context
 */
function portland_webform_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {

  // // add a custom option to the parks list for Other/Not Found. when this option is
  // // selected, the location type is changed to "I'm not sure" so that the report
  // // can be routed to 311 for triage.
  //  if (array_key_exists('#id', $element) && $element['#id'] == "location_park") {
  //   $notfound = [ '' => 'Not found'];
  //   //array_unshift($element['#options'], 'Not found');
  //   $options = $element['#options'];
  //   $element['#options'] = array('0' => 'Other / I\'m not sure') + $element['#options'];
  // } 
 
}

