FROM cimg/php:7.3-node

USER root

# From https://hub.docker.com/r/juampynr/drupal8ci/~/dockerfile/

# RUN apt-get update && apt-get install -y \
#   libpng-dev \
#   libjpeg-dev 
#   # && docker-php-ext-install -j "$(nproc)" \
#   #   gd \
#   #   pdo_mysql \
#   #   zip
