display:
  default:
    display_options:
      title: 'Job items'
      fields:
        label:
          label: लेबल
        type:
          label: प्रकार
        target_language:
          label: लाई
        tags_count:
          label: ट्यागहरू
        operations:
          label: सञ्चालनहरू
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
            first: '« पहिलो'
      exposed_form:
        options:
          reset_button_label: 'रिसेट गर्नुहोस्'
          exposed_sorts_label: क्रमबद्ध
  page_1:
    display_title: पृष्ठ
    display_options:
      menu:
        title: 'Job items'
