display:
  default:
    display_title: पूर्वनिर्धारित
    display_options:
      fields:
        filename:
          label: नाम
        filemime:
          label: 'MIME प्रकार'
        filesize:
          label: आकार
        status:
          label: अवस्था
        count:
          format_plural_string: !!binary MSBwbGFjZQNAY291bnQgcGxhY2Vz
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
      exposed_form:
        options:
          submit_button: फिल्टर
          reset_button_label: 'रिसेट गर्नुहोस्'
          exposed_sorts_label: क्रमबद्ध
      filters:
        filemime:
          expose:
            label: 'MIME प्रकार'
        status:
          expose:
            label: अवस्था
  page_2:
    display_options:
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
      arguments:
        fid:
          exception:
            title: सबै
