display:
  default:
    display_title: पूर्वनिर्धारित
    display_options:
      fields:
        file_name:
          label: नाम
        asset_type:
          label: प्रकार
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
            first: '« पहिलो'
