display:
  default:
    display_title: पूर्वनिर्धारित
    display_options:
      fields:
        asset_type:
          label: प्रकार
        mime_type:
          label: प्रकार
        filesize:
          label: आकार
        source_type:
          label: स्थान
        operations:
          label: सञ्चालनहरू
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
            first: '« पहिलो'
      exposed_form:
        options:
          reset_button_label: 'रिसेट गर्नुहोस्'
          exposed_sorts_label: क्रमबद्ध
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: वर्ग
        source_type:
          label: स्थान
