display:
  default:
    display_title: पूर्वनिर्धारित
    display_options:
      pager:
        options:
          tags:
            next: अर्को
            previous: अघिल्लो
            first: '« पहिलो'
      arguments:
        asset_id:
          exception:
            title: सबै
