<?php

/**
 * @file
 * Provides a webform composite element for picking a geographic location by map or address and
 * storing the lat-long coordinates.
 */

module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function portland_location_picker_theme() {
  return [
    'webform_example_composite' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for webform example composite templates.
 *
 * Default template: portland-location-picker.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_portland_location_picker(array &$variables) {
  // Here you can get the composite element and alter it.
  // This function resides in webform.theme.template.inc
  _template_preprocess_webform_composite($variables);
}
