<?php

/**
 * Implements hook_form_alter 
 */
function portland_location_picker_form_alter(&$form, &$form_state, $form_id) {
  // if elements array exists, this may be a webform. flatten the elements array and look for
  // the location picker field. if it exists, attach the library.
  $library_attached = false;
  if (!$library_attached && array_key_exists("elements", $form)) {
    $flattened = Drupal\webform\Utility\WebformElementHelper::getFlattened($form['elements']);
    foreach ($flattened as $key => $value) {
      if ($flattened[$key]['#type'] == "portland_location_picker") {
        $form['#attached']['library'][] = 'portland_location_picker/portland_location_picker';
        $form['#attached']['drupalSettings']['portlandmaps_api_key'] = \Drupal::service('key.repository')->getKey('portlandmaps_api')->getKeyValue();
        $library_attached = true;
        break;
      }
    }
  }
}
