<?php

/**
 * @file
 * Contains hook implementations for testing the JSON API module.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_entity_field_access().
 */
function jsonapi_test_field_access_entity_field_access($operation, FieldDefinitionInterface $field_definition) {
  // @see \Drupal\Tests\jsonapi\Functional\ResourceTestBase::testGetRelationships().
  if ($field_definition->getName() === 'field_jsonapi_test_entity_ref') {
    // Forbid access in all cases.
    return AccessResult::forbidden();
  }

  // No opinion.
  return AccessResult::neutral();
}
