<?php

/**
 * @file
 * Hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function openapi_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.openapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('@todo Add description') . '</p>';

      $output .= '</dl>';
      return $output;
  }
}
