<?php

/**
 * Implements hook_theme().
 */
function portland_content_completion_theme($existing, $type, $theme, $path) {
  return [
    'portland_content_completion_block' => [
      'variables' => [
          'completion_table' => NULL,
          'test_var' => NULL
      ],
      'template' => 'block--portland-content-completion',
    ],
    'portland_content_completion_page' => [
      'variables' => [
          'completion_table' => NULL,
          'test_var' => NULL
      ],
      'template' => 'page--portland-content-completion',
    ],
  ];
}
