display:
  default:
    display_title: Chính
    display_options:
      title: 'Job items'
      fields:
        state:
          label: Bang
        label:
          label: Nhãn
        type:
          label: Kiểu
        source_language:
          label: Từ
        target_language:
          label: Đến
        progress:
          label: 'Tiến hành'
        tags_count:
          label: Thẻ
        changed:
          label: 'đã thay đổi'
        operations:
          label: 'Thao tác'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      exposed_form:
        options:
          submit_button: 'Áp dụng'
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      filters:
        state:
          group_info:
            label: Bang
  page_1:
    display_title: Trang
    display_options:
      menu:
        title: 'Job items'
