display:
  default:
    display_title: 'Mặc định'
    display_options:
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      arguments:
        asset_id:
          exception:
            title: 'Tất cả'
