display:
  default:
    display_title: 'Mặc định'
    display_options:
      fields:
        usage_field:
          label: Phần
      arguments:
        asset_id:
          exception:
            title: 'Tất cả'
