display:
  default:
    display_title: 'Mặc định'
    display_options:
      fields:
        file_name:
          label: Tên
        asset_type:
          label: Kiểu
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
