title: 'Báo cáo Phân biệt đối xử'
elements: |
  report_discrimination:
    '#title': 'Bạn có muốn khiếu nại về chính sách của Thành phố hoặc hành động được thực hiện bởi một chương trình, nhân viên hoặc nhà thầu của Thành phố vi phạm quyền của bạn và phân biệt đối xử chống lại bạn không?'
    '#options':
      'Yes': 'Có, tôi muốn báo cáo sự phân biệt đối xử'
      'No': 'Không, nhưng tôi muốn yêu cầu một chỗ ở ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p>Vui lòng yêu cầu thông qua dịch vụ <a href="/311/ada-request">Chỗ ở ADA</a> của Thành phố. Bạn cũng có thể gọi cho chúng tôi theo <a href="tel:+1-503-823-4000">số 503-823-4000</a> hoặc TTY qua Dịch vụ chuyển tiếp Oregon: <a href="tel:711">711</a> . Nhân viên sẵn sàng trợ giúp từ Thứ Hai đến Thứ Sáu, từ 8 giờ sáng đến 5 giờ chiều</p></div>'
  report_how_to_complete:
    '#title': 'Bạn muốn hoàn thành yêu cầu hoặc báo cáo của mình như thế nào?'
    '#options':
      'Call us': 'Gọi cho chúng tôi'
      'Continue online': 'Tiếp tục trực tuyến'
  confidentiality_waiver:
    '#title': 'Từ bỏ bảo mật'
    '#description': '<p>Chính sách của Thành phố là giữ bí mật thông tin bạn cung cấp trên biểu mẫu này nhằm mục đích thực hiện yêu cầu của bạn. Thành phố cũng sẽ cố gắng giữ bí mật thông tin của bạn trong trường hợp ai đó yêu cầu nó được công bố dưới dạng hồ sơ công khai theo <a href="/attorney/oregon-public-records-law" data-renderer-mark="true">Luật Hồ sơ Công cộng</a> của Oregon. Nếu bạn muốn từ bỏ tính bảo mật này, vui lòng chọn tùy chọn đó bên dưới.</p>'
    '#options':
      'I do not waive confidentiality.': 'Tôi <em>không</em> từ bỏ tính bảo mật.'
      'I choose to waive confidentiality.': 'Tôi chọn từ bỏ tính bảo mật.'
  report_who:
    '#title': 'Quý vị đang đưa ra yêu cầu hoặc khiếu nại này cho ai?'
    '#options':
      Myself: 'Chính tôi'
      'Someone else': 'Người khác'
      'Neither of these apply to me': 'Cả hai câu trả lời này đều không đúng đối với tôi'
  report_who_neither_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Next Steps</h2><p>Completing this form starts an investigatory and potentially legal process. It is intended to be used by individuals or on behalf of individuals that believe they have been discriminated against.</p><p>If you have a concern or are attempting to point out a condition in the city that may be intentionally or unintentionally leading to the discrimination of a protected class, please use our <a href="/help/contact-elected-official">Contact an elected official form.</a></p></div>'
  report_on_behalf_of_permission:
    '#title': 'Quý vị đã được họ cho phép nộp đơn khiếu nại này chưa?'
  report_on_behalf_of_name:
    '#title': 'Tên của (những) người hoặc tổ chức bị phân biệt đối xử là gì?'
  report_third_party_relationship:
    '#title': 'Mối quan hệ của quý vị với họ là gì và tại sao quý vị lại nộp đơn cho bên thứ ba?'
  report_on_behalf_of_permission_text_stop:
    '#markup': '<h2>Bước tiếp theo</h2><p>Sau khi hoàn thành biểu mẫu này, quá trình điều tra và có thể là pháp lý sẽ bắt đầu. Biểu mẫu này được thiết kế để sử dụng cho các cá nhân hoặc tổ chức tin rằng họ đã bị phân biệt đối xử trực tiếp.</p><p>Nếu quý vị có mối lo ngại hoặc đang cố gắng chỉ ra một tình trạng trong thành phố mà có thể cố ý hoặc vô ý dẫn đến hành vi phân biệt đối xử một tầng lớp được bảo vệ, vui lòng sử dụng Biểu mẫu liên hệ với một quan chức được bầu.</p>'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p>Vui lòng gọi cho chúng tôi theo số 311, <a href="tel:+15038234000">(503) 823-4000</a> , hoặc <a href="tel:711">711</a> để biết TTY qua Dịch vụ Chuyển tiếp Oregon. Nhân viên làm việc từ Thứ Hai đến Thứ Sáu, từ 8 giờ sáng đến 5 giờ chiều, trừ các ngày Lễ của Liên bang.</p></div>'
  report_discrimination_basis:
    '#title': 'Tôi tin rằng sự phân biệt đối xử mà tôi đã trải qua là do ...'
    '#description': '<p>(Đánh dấu vào tất cả các câu phù hợp)</p>'
    '#options_none_text': 'Khác '
    '#other__option_label': 'Vui lòng mô tả '
  report_discrimination_date:
    '#title': 'Sự phân biệt đối xử xảy ra khi nào?'
  report_location:
    '#location_search__title': 'Sự việc đã xảy ra ở đâu? '
    '#place_name__title': 'Chi tiết và tên vị trí'
    '#location_details__title': 'Vui lòng cung cấp bất kỳ chi tiết nào khác có thể giúp chúng tôi xác định địa điểm mà quý vị đang báo cáo, bao gồm cả liệu địa điểm này có tên như tòa nhà công cộng hay không.'
  report_discrimination_bureau_office_etc:
    '#title': 'Vui lòng cung cấp tên của văn phòng thành phố, văn phòng, nhân viên, sự kiện hoặc chương trình liên quan đến sự phân biệt đối xử'
  report_discrimination_description:
    '#title': 'Bằng cách nói của riêng bạn, hãy mô tả sự phân biệt đối xử bị cáo buộc.'
    '#description': '<p>Hãy giải thích điều gì đã xảy ra; ai đã tham gia; chính sách, chương trình hoặc hoạt động nào là phân biệt đối xử (nếu có); tại sao bạn tin rằng điều đó đã xảy ra, và bạn bị phân biệt đối xử như thế nào. Để bảo vệ sự riêng tư của bạn, không bao gồm bất kỳ thông tin cá nhân hoặc liên quan đến sức khỏe.</p>'
  report_discrimination_witnesses:
    '#title': 'Có nhân chứng cho sự phân biệt đối xử không?'
  report_discrimination_witnesses_contact_known:
    '#title': 'Bạn có biết tên và số điện thoại hoặc địa chỉ email của họ không?'
    '#description': '<p>Nhân chứng sẽ chỉ được liên hệ nếu cần thiết để điều tra khiếu nại của bạn. Nếu được liên hệ, các nhân chứng có thể chọn xem họ có muốn tham gia vào quá trình điều tra hay không.</p>'
  report_discrimination_witness_1_name:
    '#title': 'Tên nhân chứng đầu tiên'
  report_discrimination_witness_1_phone:
    '#title': 'Nhân chứng đầu tiên điện thoại'
  report_discrimination_witness_1_email:
    '#title': 'Email của nhân chứng đầu tiên'
  report_discrimination_add_witness:
    '#title': 'Thêm nhân chứng khác?'
    '#options':
      'Add another witness': 'Thêm một nhân chứng khác'
  report_discrimination_witness_2_name:
    '#title': 'Tên nhân chứng thứ hai'
  report_discrimination_witness_2_phone:
    '#title': 'Nhân chứng thứ hai điện thoại'
  report_discrimination_witness_2_email:
    '#title': 'Email của nhân chứng thứ hai'
  report_discrimination_file_upload:
    '#title': 'Nếu thích hợp, vui lòng đính kèm bất kỳ hình ảnh hoặc tài liệu khác có liên quan đến khiếu nại của bạn.'
  report_discrimination_desired_outcome:
    '#title': 'Bạn muốn xem loại hành động hoặc giải pháp nào được thực hiện?'
  report_discrimination_filed_complaint_other:
    '#title': 'Bạn đã nộp đơn khiếu nại với bất kỳ cơ quan liên bang, tiểu bang hoặc địa phương nào khác, hoặc trong bất kỳ Tòa án Liên bang hoặc Tiểu bang nào chưa?'
    '#description': '<p>Bạn có quyền nộp đơn lên bất kỳ cơ quan hoặc tòa án nào. Nộp đơn khiếu nại với một cơ quan hoặc tòa án khác không ngăn cản bạn nộp đơn khiếu nại lên Thành phố Portland. Trong một số tình huống nhất định, các cơ quan sẽ phối hợp để đảm bảo cơ quan hoặc tòa án thích hợp điều tra đơn khiếu nại.</p>'
    '#options':
      'Yes': Đúng
      'No': Không
      'Prefer not to answer': 'không thích trả lời'
  report_discrimination_filed_complaint_other_agency:
    '#title': 'Cơ quan hay tòa án nào?'
  report_agency_contact_markup:
    '#markup': '<p>Nếu quý vị đã nộp đơn khiếu nại lên cơ quan hoặc tòa án khác, vui lòng cung cấp tên và số điện thoại hoặc địa chỉ email của bất kỳ người liên hệ nào hoặc của người đại diện đã nhận đơn khiếu nại, nếu quý vị có.</p>'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Người liên hệ của cơ quan hoặc tòa án'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Điện thoại liên hệ của cơ quan hoặc tòa án'
  report_legal_representative_name:
    '#title': 'Vui lòng cung cấp tên của người đại diện pháp lý của quý vị, nếu có.'
  report_legal_representative_contact_number:
    '#title': 'Vui lòng cung cấp thông tin liên hệ của người đại diện pháp lý của quý vị, nếu có.'
  contact_name:
    '#title': 'Tên của bạn'
  contact_email:
    '#title': E-mail
    '#description': '<p>Chúng tôi sẽ sử dụng email của bạn để xác nhận nội dung bạn gửi.</p>'
  contact_phone:
    '#title': 'Điện thoại'
  contact_preferred_method:
    '#title': 'Nếu cần, bạn có muốn chúng tôi liên hệ với bạn qua điện thoại hoặc email không?'
    '#options':
      Phone: 'Điện thoại'
      Email: E-mail
  contact_interpreter:
    '#title': 'Bạn có cần thông dịch viên không?'
    '#options':
      'No': Không
      'Yes, VRI (Video Remote Interpretation)': 'Có, VRI (Phiên dịch từ xa bằng video)'
      'Yes, Oregon Relay Service': 'Có, Dịch vụ chuyển tiếp Oregon'
      'Yes, language interpreter': 'Có, thông dịch viên ngôn ngữ'
  contact_language:
    '#title': 'Ngôn ngữ nào?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Lời xác nhận của người khiếu nại</strong></p><p>Bằng cách gửi biểu mẫu này, tôi khẳng định rằng (1) Tôi đã đọc, hiểu và chấp nhận các <a href="/code/23">điều khoản về thủ tục theo dõi và điều tra các khiếu nại về Quyền Dân sự</a> và (2) Thông tin tôi cung cấp trong biểu mẫu này là đúng theo hiểu biết của tôi.</p>'
  complainant_acknowledgement_agree:
    '#title': 'tôi đồng ý'
  actions:
    '#title': 'Gửi (các) nút'
    '#submit__label': Nộp
  report_ticket_id:
    '#title': 'Báo cáo ID vé'
settings:
  confirmation_title: ''
  confirmation_message: ''
handlers:
  zendesk_new_ticket:
    label: 'Vé mới của Zendesk'
    notes: 'Tạo phiếu khiếu nại về Phân biệt đối xử mới và giao nó cho nhóm 311: ADA và Phân biệt đối xử.'
