title: 'Yêu cầu chỗ ở của ADA'
elements: |
  request_how:
    '#title': 'Bạn muốn thực hiện yêu cầu của mình như thế nào?'
    '#options':
      'I would like to call the City': 'Tôi muốn liên hệ với Thành phố qua điện thoại hoặc TTY'
      'I will continue with the online form': 'Tôi sẽ tiếp tục với biểu mẫu trực tuyến'
  markup_continue:
    '#markup': '<p class="mt-5"><strong>Vui lòng chọn để tiếp tục.</strong></p>'
  request_call_city_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p>Vui lòng gọi cho chúng tôi theo <a href="tel:311">số 311</a> , <a href="tel:+15038234000">(503) 823-4000</a> , hoặc <a href="tel:711">711</a> để biết TTY qua Dịch vụ Chuyển tiếp Oregon. Nhân viên làm việc từ Thứ Hai đến Thứ Sáu, từ 8 giờ sáng đến 5 giờ chiều, trừ các ngày Lễ của Liên bang.</p></div>'
  request_who:
    '#title': 'Bạn đang đưa ra yêu cầu hoặc khiếu nại này cho ai?'
    '#options':
      Myself: 'Chính tôi'
      'Someone else': 'Một người khác'
      'Neither of these apply to me': 'Cả hai điều này đều không áp dụng cho tôi.'
  request_who_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Thông tin</h2><p>Bằng việc lựa chọn tùy chọn này, tôi xác nhận rằng tôi có một khuyết tật thuộc phạm vi điều chỉnh của Đạo luật Người khuyết tật Hoa Kỳ (Americans with Disabilities Act), và rằng các thông tin tôi cung cấp trong biểu mẫu này là đúng sự thật, theo hiểu biết và niềm tin tốt nhất của tôi.</p></div>'
  request_someone_else_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Thông tin</h2><p>Bằng việc lựa chọn tùy chọn này, tôi xin xác nhận rằng người mà tôi đang thực hiện yêu cầu hoặc khiếu nại này thay mặt có một khuyết tật thuộc phạm vi điều chỉnh của Đạo luật Người khuyết tật Hoa Kỳ (Americans with Disabilities Act), và rằng các thông tin tôi cung cấp trong biểu mẫu này là đúng sự thật, theo hiểu biết và niềm tin tốt nhất của tôi.</p></div>'
  request_who_neither_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Thông tin</h2><p>Lựa chọn này được sử dụng khi quý vị muốn báo cáo một quan sát, vấn đề hoặc mối lo ngại mà quý vị tin rằng có thể ảnh hưởng hoặc gây ra mối đe dọa đối với công chúng, đặc biệt là những người khuyết tật. Vui lòng liên hệ với chúng tôi qua số <a href="tel:311">311</a> hoặc địa chỉ email <a href="311@portlandoregon.gov">311@portlandoregon.gov</a> để được hỗ trợ.</p></div>'
  request_on_behalf_of_permission:
    '#title': 'Bạn đã nhận được sự cho phép từ họ để nộp đơn khiếu nại này chưa? Hoặc, bạn có mối quan hệ pháp lý nào cho phép bạn thực hiện việc khiếu nại thay mặt cho họ hay không?'
  request_on_behalf_of_name:
    '#title': 'Tên của họ là gì?'
  request_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Các bước tiếp theo</h2><p>Vui lòng xin phép họ trước khi gửi biểu mẫu này.</p></div>'
  container_confidentiality:
    '#title': 'Bảo mật'
  confidentiality_waiver:
    '#title': 'Từ bỏ bảo mật'
    '#description': '<p>Chính sách của Thành phố là giữ bí mật thông tin bạn cung cấp trên biểu mẫu này. Thông tin của bạn sẽ được giữ bí mật trừ khi bạn đánh dấu vào ô xác nhận rằng bạn muốn từ bỏ tính bảo mật.</p>'
    '#options':
      'I do not waive confidentiality': 'Tôi <em>không</em> từ bỏ tính bảo mật.'
      'I waive confidentiality': 'Tôi chọn từ bỏ tính bảo mật.'
  request_what:
    '#title': 'Tôi muốn yêu cầu Thành phố ...'
    '#options':
      event_accommodations: 'Cung cấp chỗ ở cho một hoạt động, sự kiện hoặc chương trình của Thành phố'
      parks_activity_registration: 'Cung cấp các hỗ trợ điều chỉnh cho quy trình đăng ký và thiết lập tài khoản đối với các hoạt động của Portland Parks & Recreation.'
      city_materials: 'Cung cấp tài liệu về Thành phố ở định dạng mà tôi có thể truy cập được'
      app_accessibility: 'Khắc phục sự cố về khả năng tiếp cận đối với ứng dụng hoặc trang web của Thành phố'
      remove_barrier: 'Loại bỏ rào cản hoặc giúp tôi tiếp cận đường phố, vỉa hè, đường nhỏ, công viên hoặc không gian khác thuộc sở hữu của Thành phố dễ dàng hơn (chẳng hạn như loại bỏ chướng ngại vật trên vỉa hè, thêm lối đi qua đường hoặc cải thiện biển báo)'
      change_policy: 'Thay đổi hoặc sửa đổi chính sách hoặc thủ tục (ví dụ: cho phép các thành viên cộng đồng khuyết tật sớm tham gia một sự kiện, cho phép một người bạn đồng hành tham gia một lớp học hoặc hoạt động)'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Vui lòng mô tả yêu cầu của bạn. Không bao gồm bất kỳ thông tin cá nhân hoặc thông tin liên quan đến sức khỏe nào.'
  request_parks_assistance:
    '#title': 'Bạn cần loại hỗ trợ nào?'
    '#options':
      'Setting up my ActiveNet account (the system Portland Parks and Recreation uses for class/recreation registrations)': 'Thiết lập tài khoản ActiveNet của tôi (hệ thống mà Portland Parks and Recreation sử dụng để đăng ký các lớp học và hoạt động giải trí).'
      'Instructions and resources to help me get signed up for upcoming recreation activities': 'Hướng dẫn và tài nguyên giúp tôi đăng ký tham gia các hoạt động giải trí sắp tới.'
  container_materials:
    '#title': 'Yêu cầu tài liệu'
  request_materials_type:
    '#title': 'Vật liệu bạn đang yêu cầu có phải ...'
    '#options':
      website: 'trên trang web của Thành phố?'
      event: 'cho một sự kiện hoặc hoạt động cụ thể?'
      printed: 'một tài liệu in không có sẵn trực tuyến?'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Hãy mô tả các vật liệu.'
  request_materials_url:
    '#title': 'Địa chỉ web (URL) của trang chứa tài liệu là gì?'
  request_materials_description:
    '#title': 'Tên và / hoặc mô tả của tài liệu'
  page_you_last_viewed:
    '#title': 'Trang bạn đã xem lần cuối'
  continue_button:
    '#markup': '<p><a class="button button--primary" href="/feedback?page_you_last_viewed=[server:HTTP_REFERER]&amp;subject=Fix%20an%20accessibility%20issue%20with%20a%20City%20app%20or%20website" aria-label="Tiếp tục báo cáo vấn đề về khả năng tiếp cận đối với ứng dụng hoặc trang web của thành phố">Tiếp tục báo cáo sự cố ứng dụng hoặc trang web</a></p>'
  container_event:
    '#title': 'chi tiết sự kiện'
  request_event_name:
    '#title': 'Tên hoạt động, sự kiện hoặc chương trình'
  request_event_date:
    '#title': 'Ngày sự kiện'
  request_event_location:
    '#title': 'Vị trí của sự kiện'
  request_event_bureau_sponsor:
    '#title': 'Người tổ chức sự kiện'
    '#description': '<p>Vui lòng nêu rõ văn phòng, văn phòng, chương trình, dự án của Thành phố hoặc quan chức được bầu cử đang tổ chức sự kiện, nếu bạn biết.</p>'
  request_event_url:
    '#title': 'URL chi tiết sự kiện'
    '#description': '<p>Vui lòng sao chép và dán địa chỉ URL của sự kiện, chương trình hoặc trang web của tài liệu, nếu biết.</p>'
  container_event_accommodations:
    '#title': 'Phòng tổ chức sự kiện'
  request_event_accommodations_type:
    '#title': 'Bạn đang yêu cầu loại chỗ ở nào?'
    '#description': '<p>Đánh dấu vào tất cả các câu phù hợp.</p>'
    '#options':
      accessible_parking: 'Bãi đậu xe cho người sử dụng'
      accessible_entrance: 'Lối vào sự kiện và các tuyến đường dẫn đến phòng vệ sinh'
      communication_aids: 'Hỗ trợ giao tiếp'
      accessible_materials: 'Vật liệu ở định dạng có thể truy cập được'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Vui lòng mô tả yêu cầu của bạn. Không bao gồm bất kỳ thông tin cá nhân hoặc thông tin liên quan đến sức khỏe nào.'
  request_event_communiation_aids_type:
    '#title': 'Bạn thích loại công cụ hỗ trợ truyền thông nào hơn?'
    '#options':
      captioning: 'Chú thích'
      listening_device: 'Thiết bị nghe hỗ trợ'
      interpretation_asl: 'Phiên dịch bằng ASL'
      interpretation_other: 'Phiên dịch bằng một ngôn ngữ ký hiệu hoặc xúc giác khác'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Vui lòng mô tả yêu cầu của bạn. Không bao gồm bất kỳ thông tin cá nhân hoặc thông tin liên quan đến sức khỏe nào.'
  request_event_materials_format:
    '#title': 'Bạn thích định dạng tài liệu sự kiện nào hơn?'
    '#options':
      accessble_word_doc: 'Tài liệu điện tử có thể truy cập (Microsoft Word)'
      accessible_pdf: 'Tài liệu điện tử có thể truy cập (PDF)'
      large_print: 'Giấy in khổ lớn'
      braille: 'Chữ nổi'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Vui lòng mô tả yêu cầu của bạn. Không bao gồm bất kỳ thông tin cá nhân hoặc thông tin liên quan đến sức khỏe nào.'
  container_remove_barrier:
    '#title': 'Loại bỏ rào cản'
  request_barrier_type:
    '#title': 'Bạn đang báo cáo loại vấn đề nào? Làm cách nào chúng tôi có thể giúp bạn truy cập dễ dàng hơn?'
    '#options':
      barrier: 'Rào cản - Có rào cản, vật cản hoặc thứ gì đó cản trở việc tiếp cận'
      parking: 'Bãi đậu xe - Không có chỗ đậu xe cho phép sử dụng hoặc có vấn đề với các điểm hiện có'
      signage: 'Biển báo - Không có biển báo hoặc biển báo không rõ ràng'
    '#other__option_label': 'Thứ gì khác...'
    '#other__description': 'Làm ơn miêu tả.'
  report_location:
    '#title': 'Vị trí của rào cản hoặc vấn đề'
    '#location_search__title': 'Tìm kiếm địa điểm'
    '#location_map__title': 'Bản đồ địa điểm'
    '#suggestions_modal__title': 'Gợi ý'
    '#status_modal__title': 'Chỉ báo trạng thái'
    '#location_address__title': 'Địa chỉ hoặc đường chéo'
    '#location_lat__title': 'Vĩ độ'
    '#location_lon__title': 'Kinh độ'
    '#place_name__title': 'Tên địa điểm'
    '#location_details__title': 'Chi tiết vị trí'
    '#location_asset_id__title': 'ID nội dung'
  report_barrier_description:
    '#title': 'Mô tả vấn đề'
    '#description': '<p>Vui lòng mô tả vấn đề chi tiết. Làm cách nào để chúng tôi có thể tiếp cận thành phố của bạn dễ dàng hơn? Để bảo vệ sự riêng tư của bạn, không bao gồm bất kỳ thông tin cá nhân hoặc liên quan đến sức khỏe.</p>'
  container_change_policy:
    '#title': 'Thay đổi chính sách'
  report_policy_request:
    '#title': 'Yêu cầu của bạn là gì?'
    '#description': '<p>Vui lòng mô tả chính sách hoặc thay đổi thủ tục mà bạn đang yêu cầu. Để bảo vệ sự riêng tư của bạn, không bao gồm bất kỳ thông tin cá nhân hoặc liên quan đến sức khỏe.</p>'
  section_contact:
    '#title': 'Thông tin liên lạc'
  contact_name:
    '#title': 'Tên của bạn'
  contact_email:
    '#title': 'Email của bạn'
    '#description': '<p>Chúng tôi sẽ sử dụng email của bạn để trả lời phản hồi hoặc yêu cầu của bạn.</p>'
  contact_phone:
    '#title': 'Điện thoại'
  contact_phone_assistance_type:
    '#title': 'Nếu bạn cần hỗ trợ qua điện thoại, vui lòng chọn một tùy chọn'
    '#options':
      vri: VRI
      relay: 'Dịch vụ chuyển tiếp Oregon (TTY)'
      interpreter: 'Thông dịch viên'
      none: 'Không có cái nào ở trên'
  support_agent_use_only:
    '#title__title': ''
  report_ticket_id:
    '#title': 'Báo cáo ID vé'
  computed_location_address:
    '#title': 'Địa chỉ Vị trí được Tính toán'
  computed_location_latlon:
    '#title': 'Vị trí được tính toán Latlon'
  actions:
    '#title': 'Gửi (các) nút'
    '#submit__label': Nộp
settings:
  confirmation_title: 'Cảm ơn bạn đã gửi yêu cầu của bạn!'
  confirmation_message: '<p>Yêu cầu của bạn đã được nhận và bạn sẽ được liên hệ trong vòng 48 giờ.</p>'
handlers:
  zendesk_new_ticket:
    label: 'Vé mới của Zendesk'
    notes: 'Tạo một phiếu Yêu cầu Chỗ ở mới của ADA và giao nó cho nhóm 311.'
