title: 'Phản hồi trang web'
description: '<p>Biểu mẫu web này được sử dụng để thu thập phản hồi về trang web từ người dùng và người chỉnh sửa.</p>'
elements: |
  subject:
    '#title': 'Loại phản hồi'
    '#options':
      "I cannot find what I'm looking for": 'Tôi không thể tìm thấy những gì tôi đang tìm kiếm'
      'I have a question': 'tôi có một câu hỏi'
      'The page looks broken': 'Trang có vẻ bị hỏng'
      'The information looks incorrect': 'Thông tin có vẻ không chính xác'
      'Contact an elected official with feedback': 'Liên hệ với một quan chức được bầu để cung cấp thông tin phản hồi'
      'Fix an accessibility issue with a City app or website': 'Khắc phục sự cố về khả năng tiếp cận đối với ứng dụng hoặc trang web của Thành phố'
    '#empty_option': '-- Lựa chọn --'
  link_to_contact_elected:
    '#markup': '<div class="alert alert--info next-steps"><h2>Bước tiếp theo</h2><p>Vui lòng sử dụng biểu mẫu <a href="/help/contact-elected-official">Liên hệ với một quan chức được bầu chọn</a> để gửi phản hồi của bạn hoặc yêu cầu một cuộc họp.</p></div>'
  feedback:
    '#title': 'Thông tin chi tiết'
    '#description': '<p>Vui lòng nêu cụ thể để chúng tôi có thể hỗ trợ bạn tốt hơn.</p>'
  your_name:
    '#title': 'Tên của bạn'
  email_address:
    '#title': 'Email của bạn'
  page_you_last_viewed:
    '#title': 'Trang bạn xem lần cuối'
    '#description': '<p>Bạn có thể thay đổi địa chỉ này nếu bạn muốn bình luận trên một trang khác.</p>'
    '#default_value': '[máy chủ: HTTP_REFERER]'
  public_records_statement:
    '#markup': '<p>Thông tin bạn cung cấp trong biểu mẫu này được coi là hồ sơ công khai theo <a href="/attorney/oregon-public-records-law" data-renderer-mark="true">Luật Hồ sơ Công cộng</a> của Oregon và có sẵn cho công chúng theo yêu cầu.</p>'
  support_agent_use_only:
    '#title__title': ''
  actions:
    '#title': 'Gửi (các) nút'
  ip_address:
    '#title': 'Địa chỉ IP'
settings:
  form_close_message: '<p>Biểu mẫu phản hồi của chúng tôi tạm thời bị đóng. Nếu bạn có phản hồi hoặc đề xuất về cách chúng tôi có thể cải thiện trang này, hãy gửi email cho nhóm web tại powr@portlandoregon.gov.</p>'
  confirmation_message: '<h2>Cảm ơn bạn đã gửi phản hồi, chúng tôi đánh giá cao sự giúp đỡ của bạn!</h2><p>Bạn sẽ nhận được email xác nhận chỉ trong giây lát. Bạn có thể trả lời email đó để thêm thông tin hoặc nhận xét bổ sung vào phản hồi của mình.<br><br>Tên: [webform_submission: giá trị: your_name]<br><br>Email: [webform_submission: giá trị: email_address]<br><br>Loại phản hồi: [webform_submission: giá trị: chủ đề]<br><br>Trang được xem lần cuối: <a href="[webform_submission:values:page_you_last_viewed]">[webform_submission: giá trị: page_you_last_viewed]</a><br><br>Phản hồi: [webform_submission: giá trị: phản hồi]</p>'
handlers:
  submit_report_to_311:
    label: 'Gửi báo cáo đến 311'
    notes: ''
    settings:
      from_name: ''
      subject: '[webform_submission: giá trị: chủ đề: raw] - [webform_submission: giá trị: phản hồi]'
      body: '<p>Chủ đề: [webform_submission: giá trị: chủ đề]</p><p>Phản hồi: [webform_submission: giá trị: phản hồi]</p><p>Tên: [webform_submission: giá trị: your_name]</p><p>Email: [webform_submission: giá trị: email_address]</p><p>Trang được xem lần cuối: [webform_submission: giá trị: page_you_last_viewed]</p><p>Đã gửi vào: [webform_submission: created]</p><p>Tác nhân người dùng: [máy chủ: HTTP_USER_AGENT]</p><p>[webform_submission: giá trị: agent_summary]</p>'
  submit_report_to_website_support:
    label: 'Gửi báo cáo đến bộ phận hỗ trợ trang web'
    notes: ''
    settings:
      from_name: ''
      subject: '[webform_submission: giá trị: chủ đề: raw] - [webform_submission: giá trị: phản hồi]'
      body: '<p>Chủ đề: [webform_submission: giá trị: chủ đề]</p><p>Phản hồi: [webform_submission: giá trị: phản hồi]</p><p>Tên: [webform_submission: giá trị: your_name]</p><p>Email: [webform_submission: giá trị: email_address]</p><p>Trang được xem lần cuối: [webform_submission: giá trị: page_you_last_viewed]</p><p>Đã gửi vào: [webform_submission: created]</p><p>Tác nhân người dùng: [máy chủ: HTTP_USER_AGENT]<br><br>[webform_submission: giá trị: agent_summary]</p>'
