elements: |
  report_confirm_non_emergency:
    '#title': 'Đây có phải là vấn đề khẩn cấp, đe dọa đến tính mạng, trong đó có người bị thương hoặc đang có đám cháy hay không?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Vui lòng ngừng điền mẫu đơn này và gọi 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Vui lòng chọn một mục để tiếp tục.</strong></p>'
  markup:
    '#markup': '<p><em><strong>Trong những thời điểm có lượng cuộc gọi/báo cáo cao trong năm, lực lượng thực thi pháp luật không có đủ nguồn lực để phản hồi tất cả các cuộc gọi không khẩn cấp. Các Điều tra viên Phòng cháy Chữa cháy sẽ điều tra tất cả các vụ cháy có liên quan đến pháo hoa, và những người vi phạm sẽ phải chịu trách nhiệm.&nbsp;</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Vui lòng chia sẻ địa điểm của quý vị khi nghe thấy tiếng pháo hoa nổ'
    '#location_address__description': 'Ví dụ: địa chỉ nhà của quý vị'
    '#unit_number__title': 'Số căn hộ/phòng'
    '#location_city__title': 'Thành phố'
    '#location_state__title': 'Tiểu bang'
    '#location_zip__title': 'Mã ZIP'
  report_confirm_known_location:
    '#title': 'Quý vị có biết địa điểm nơi pháo hoa đang được đốt/bắn hay không?'
  report_incident_location:
    '#title': 'Địa điểm Xảy ra Vụ việc'
  report_location:
    '#location_search__title': 'Tìm kiếm Địa điểm'
    '#location_search__description': 'Tìm kiếm địa chỉ, giao lộ, công viên hoặc trung tâm cộng đồng trên bản đồ. Hoặc sử dụng bản đồ để nhấp chọn một địa điểm.'
    '#location_details__title': 'Chi tiết Địa điểm'
    '#location_details__description': 'Vui lòng cung cấp bất kỳ thông tin chi tiết nào khác có thể giúp chúng tôi xác định địa điểm mà quý vị đang báo cáo.'
  report_date:
    '#title': 'Ngày Xảy ra Vụ việc'
  report_time:
    '#title': 'Thời gian Ước tính Xảy ra Vụ việc'
  report_incident_description:
    '#title': 'Cung cấp bất kỳ mô tả hữu ích nào về vụ việc'
    '#description': '<p>Ví dụ: màu sắc của ngôi nhà, chủ sở hữu, các phương tiện liên quan, việc quý vị có video hoặc tệp phương tiện ghi lại vụ việc hay không. Nếu cần thiết, sẽ có người liên hệ với quý vị để hướng dẫn cách gửi ảnh hoặc video.</p>'
  section_contact:
    '#title': 'Thông tin Liên hệ của Quý vị'
    '#description': '<p>Xin lưu ý: Do nguồn lực hạn chế, quý vị KHÔNG nên kỳ vọng sẽ nhận được phản hồi đối với báo cáo này.</p>'
  contact_name:
    '#title': Tên
  contact_email:
    '#description': '<p>Chúng tôi sẽ sử dụng email của quý vị để xác nhận việc gửi báo cáo.</p>'
  contact_phone:
    '#title': 'Điện thoại'
  section_confidentiality:
    '#title': 'Bảo mật'
  confidentiality_waiver:
    '#title': 'Từ bỏ Quyền Bảo mật'
    '#description': '<p>Theo chính sách của Thành phố, thông tin quý vị cung cấp trong mẫu đơn này sẽ được giữ bảo mật nhằm mục đích xử lý yêu cầu của quý vị. Thành phố cũng sẽ cố gắng giữ bảo mật thông tin của quý vị trong trường hợp có người yêu cầu công khai thông tin đó dưới dạng hồ sơ công theo <a href="/attorney/oregon-public-records-law">Luật Hồ sơ Công của Oregon</a>. Nếu quý vị muốn từ bỏ quyền bảo mật này, vui lòng chọn tùy chọn đó bên dưới</p>'
    '#options':
      'I do not waive confidentiality': 'Tôi <em>không</em> từ bỏ quyền bảo mật.'
      'I waive confidentiality': 'Tôi chọn từ bỏ quyền bảo mật.'
settings:
  confirmation_title: 'Cảm ơn quý vị đã gửi khiếu nại!'
  confirmation_message: '<p>Báo cáo của quý vị (#[webform_submission:values:report_ticket_id]) đã được tiếp nhận.</p><p>Trong những thời điểm có lượng cuộc gọi/báo cáo cao trong năm, lực lượng thực thi pháp luật không có đủ nguồn lực để phản hồi tất cả các cuộc gọi không khẩn cấp. Mặc dù hiện không có đủ nguồn lực để phản hồi phần lớn các khiếu nại về pháo hoa, chúng tôi vẫn đang thu thập thông tin để phục vụ các nỗ lực đang được triển khai nhằm bảo đảm việc tuân thủ Lệnh cấm Pháo hoa. Quý vị KHÔNG nên kỳ vọng sẽ nhận được cuộc gọi lại liên quan đến báo cáo này.</p><p>Các Điều tra viên Phòng cháy Chữa cháy sẽ điều tra tất cả các vụ cháy có liên quan đến pháo hoa, và những người vi phạm sẽ phải chịu trách nhiệm.</p><p>Nếu tình huống liên quan đến pháo hoa có người bị thương hoặc có đám cháy, hãy gọi 911.&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>Cảm ơn quý vị đã gửi khiếu nại!</h2><p>Báo cáo của quý vị (#[webform_submission:values:report_ticket_id]) đã được tiếp nhận.</p><p>Trong những thời điểm có lượng cuộc gọi/báo cáo cao trong năm, lực lượng thực thi pháp luật không có đủ nguồn lực để phản hồi tất cả các cuộc gọi không khẩn cấp. Mặc dù hiện không có đủ nguồn lực để phản hồi phần lớn các khiếu nại về pháo hoa, chúng tôi vẫn đang thu thập thông tin để phục vụ các nỗ lực đang được triển khai nhằm bảo đảm việc tuân thủ Lệnh cấm Pháo hoa. Quý vị KHÔNG nên kỳ vọng sẽ nhận được cuộc gọi lại liên quan đến báo cáo này.</p><p>Các Điều tra viên Phòng cháy Chữa cháy sẽ điều tra tất cả các vụ cháy có liên quan đến pháo hoa, và những người vi phạm sẽ phải chịu trách nhiệm.</p><p>Nếu tình huống liên quan đến pháo hoa có người bị thương hoặc có đám cháy, hãy gọi 911.&nbsp;</p>'
