<?php

use Drupal\webform\Utility\WebformElementHelper;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;

function portland_webforms_help($route_name, $route_match) {
  \Drupal::logger('portland_webforms')->notice('Portland Webforms module loaded');
}

/**
 * Implements hook_form_alter 
 */
function portland_webforms_form_alter(&$form, &$form_state, $form_id) {
  // if elements array exists, this may be a webform. flatten the elements array and look for
  // the location picker field. if it exists, attach the library.
  $library_attached = false;
  if (!$library_attached && array_key_exists("elements", $form)) {
    $flattened = WebformElementHelper::getFlattened($form['elements']);
    foreach ($flattened as $key => $value) {
      if (array_key_exists('#type', $flattened[$key]) && $flattened[$key]['#type'] == "portland_location_widget") {
        $form['#attached']['library'][] = 'portland_webforms/portland_location_widget';
        $form['#attached']['drupalSettings']['portlandmaps_api_key'] = \Drupal::service('key.repository')->getKey('portlandmaps_api')->getKeyValue();
        $library_attached = true;
        break;
      }
    }
  }
}

/**
 * Implements hook_webform_element_alter().
 *
 * @param array              $element
 * @param FormStateInterface $form_state
 * @param array              $context
 */
function portland_portland_webforms_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {

  // TODO: need a better way to handle this. in some forms, the location widget may be hidden due to conditional
  // logic and never used, but this is causing it to still require a value. Can we make sub-elements conditionally
  // required? Or can we detect whether the parent element is conditionally required?
  
  // // add a custom validation constraint to the map element; 
  // // it will check lat/lng to validate that a location has been selected.
  // if (array_key_exists('#id', $element) && $element['#id'] == "location_map") {
  //   $element['#element_validate'][] = [
  //       'Drupal\portland_location_picker\Validate\GeolocationValidationConstraint',
  //       'validate'
  //   ];
  // } 

 
}

