<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter() for our custom element.
 */
function portland_webforms_webform_element_portland_ajax_indicator_alter(array &$element, FormStateInterface $form_state, array $context) {
  $element['#attached']['library'][] = 'portland_webforms/portland_ajax_indicator';
}

/**
 * Implements hook_form_alter().
 */
function portland_webforms_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Attach to any Webform submission form for this specific webform.
  if (!empty($form['#webform_id']) && $form['#webform_id'] === 'council_district_lookup') {
    $form['#attached']['library'][] = 'portland_webforms/council_district_lookup';
  }
}