<?php

use Drupal\webform\Utility\WebformElementHelper;

function portland_webforms_help($route_name, $route_match) {
  \Drupal::logger('portland_webforms')->notice('Portland Webforms module loaded');
}

/**
 * Implements hook_form_alter 
 */
function portland_webforms_form_alter(&$form, &$form_state, $form_id) {
  // if elements array exists, this may be a webform. flatten the elements array and look for
  // the supported elements. if they exists, attach their libraries.
  $ajax_indicator_attached = false;
  $location_widget_attached = false;

  if ((!$ajax_indicator_attached || !$location_widget_attached) && array_key_exists("elements", $form)) {
    $flattened = WebformElementHelper::getFlattened($form['elements']);
    foreach ($flattened as $key => $value) {
      // attach spinner?
      if (!$ajax_indicator_attached && array_key_exists('#type', $flattened[$key]) && $flattened[$key]['#type'] == "portland_ajax_indicator") {
        $form['#attached']['library'][] = 'portland_webforms/portland_ajax_indicator';
        $ajax_indicator_attached = true;
        break;
      }
    }
  }
}

