label: 'مكتبة الوسائط'
display:
  default:
    display_title: الافتراضي
    display_options:
      title: وسائط
      fields:
        media_bulk_form:
          action_title: إجراء
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: 'عمل تصفية'
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      empty:
        area_text_custom:
          content: 'لا توجد وسائط متاحة.'
      sorts:
        created:
          expose:
            label: 'الأحدث أولاً'
        name:
          expose:
            label: 'الاسم (أ-ي)'
        name_1:
          expose:
            label: 'الاسم (ي-أ)'
      filters:
        status:
          expose:
            label: 'حالة النشر'
          group_info:
            label: منشور
        name:
          expose:
            label: الاسم
        langcode:
          expose:
            label: اللغة
  page:
    display_title: الصفحة
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
        name:
          separator: ', '
        edit_media:
          alter:
            text: 'تحرير {{ name }}'
            alt: 'تحرير {{ name }}'
          text: تحرير
        delete_media:
          alter:
            text: 'حذف {{ اسم }}'
            alt: 'حذف {{ اسم }}'
          text: حذف
  widget:
    display_title: 'عنصر إدخال (ودجت)'
    display_options:
      arguments:
        bundle:
          exception:
            title: الكل
      header:
        display_link_grid:
          label: شبكة
        display_link_table:
          label: جدول
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: 'النسخة المصغرة'
        name:
          label: الاسم
        uid:
          label: المؤلف
        changed:
          label: 'تم التحديث'
      arguments:
        bundle:
          exception:
            title: الكل
      header:
        display_link_grid:
          label: شبكة
        display_link_table:
          label: جدول
