label: Watchdog
description: 'آخر رسائل السجل'
display:
  default:
    display_title: الافتراضي
    display_options:
      title: 'آخر رسائل السجل'
      fields:
        nothing:
          admin_label: أيقونة
        severity:
          label: الحدة
        type:
          label: النوع
        timestamp:
          label: التاريخ
        message:
          label: الرسالة
        name:
          label: مستخدم
          separator: ', '
        link:
          label: العمليات
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: تصفية
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      empty:
        area:
          admin_label: 'لا توجد رسائل سجل متاحة.'
          content: 'لا توجد رسائل سجل متاحة.'
      filters:
        type:
          expose:
            label: النوع
        severity:
          expose:
            label: الحدة
  page:
    display_title: الصفحة
