display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        source_entity_id:
          label: 'معرّف الكينونة'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      arguments:
        asset_id:
          exception:
            title: الكل
