display:
  default:
    display_title: الافتراضي
    display_options:
      pager:
        options:
          tags:
            next: 'التالي ›'
            previous: '‹ السابق'
            first: '« الأولى'
            last: 'الأخيرة »'
      arguments:
        asset_id:
          exception:
            title: الكل
