display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        fid:
          label: 'معرف الملف'
        asset_type:
          label: النوع
        mime_type:
          label: النوع
        filesize:
          label: الحجم
        source_type:
          label: الموقع
        operations:
          label: العمليات
      pager:
        options:
          tags:
            next: 'التالي ›'
            previous: '‹ السابق'
            first: '« الأولى'
            last: 'الأخيرة »'
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      filters:
        category:
          group_info:
            group_items:
              10:
                title: آخر
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: الفئة
        mime_type:
          label: 'نوع مايم'
        source_type:
          label: الموقع
        filesize_formatted:
          separator: ', '
        active_use_csv:
          separator: ', '
        used_in_csv:
          separator: ', '
