display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تصفية
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
          tags:
            previous: '‹ السابق'
            next: 'التالي ›'
            first: '« الأولى'
            last: 'الأخيرة »'
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        title:
          label: التسمية
          separator: ', '
        item_count:
          label: عناصر
      filters:
        status:
          expose:
            label: الحالة
  closed:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
      menu:
        title: مغلق
  completed:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
      menu:
        title: 'تم الإنهاء'
  eligible:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
  my_tasks:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
  pending:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
          separator: ', '
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
      menu:
        title: معلّق
  rejected:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        title:
          expose:
            label: التسمية
  unassigned:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: التسمية
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        operations:
          label: العمليات
      filters:
        status:
          expose:
            label: الحالة
      tab_options:
        title: ترجمة
