display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ السابقة'
            next: 'التالية ›'
            first: '« الأولى'
            last: 'الأخيرة »'
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        created:
          label: 'تم الإنشاء'
        label:
          label: عنصر
        name:
          label: الاسم
          separator: ', '
      title: الرسائل
      arguments:
        tjid:
          exception:
            title: الكل
  embed:
    display_title: تضمين
