display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تصفية
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ السابق'
            next: 'التالي ›'
            first: '« الأولى'
            last: 'الأخيرة »'
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        title:
          label: العنوان
          separator: ', '
        item_count:
          label: عناصر
  assigned:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
          separator: ', '
        tuid:
          separator: ', '
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
      filters:
        source_language:
          expose:
            label: 'لغة المصدر'
        uid:
          expose:
            label: المزود
        title:
          expose:
            label: العنوان
  closed:
    display_title: مغلق
    display_options:
      menu:
        title: مغلق
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
          separator: ', '
        created:
          label: 'تم الإنشاء'
          separator: ', '
        tuid:
          separator: ', '
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
      filters:
        source_language:
          expose:
            label: 'لغة المصدر'
        uid:
          expose:
            label: المزود
        title:
          expose:
            label: العنوان
  completed:
    display_title: 'تم الإنهاء'
    display_options:
      menu:
        title: 'تم الإنهاء'
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
          separator: ', '
        created:
          label: 'تم الإنشاء'
          separator: ', '
        tuid:
          separator: ', '
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
      filters:
        source_language:
          expose:
            label: 'لغة المصدر'
        uid:
          expose:
            label: المزود
        title:
          expose:
            label: العنوان
  pending:
    display_title: معلّق
    display_options:
      menu:
        title: معلّق
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        tuid:
          separator: ', '
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
      filters:
        source_language:
          expose:
            label: 'لغة المصدر'
        uid:
          expose:
            label: المزود
        title:
          expose:
            label: العنوان
  rejected:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        created:
          label: 'تم الإنشاء'
          separator: ', '
        tuid:
          separator: ', '
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
      filters:
        source_language:
          expose:
            label: 'لغة المصدر'
        uid:
          expose:
            label: المزود
        title:
          expose:
            label: العنوان
  unassigned:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'تحديث شامل'
        status:
          label: الحالة
        title:
          label: العنوان
          separator: ', '
        source_language:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        item_count:
          label: عناصر
        loop_count:
          separator: ', '
        operations:
          label: العمليات
