display:
  default:
    display_title: الرئيسي
    display_options:
      fields:
        state:
          label: الحالة
          separator: ', '
        label:
          label: التسمية
        source_language_1:
          label: من
          separator: ', '
        target_language:
          label: إلى
          separator: ', '
        translator:
          label: المزود
        tags_count:
          label: وسوم
        changed:
          label: 'تم التغير'
        operations:
          label: العمليات
      pager:
        options:
          tags:
            next: 'التالية ›'
            previous: '‹ السابقة'
            first: '« الأولى'
            last: 'الأخيرة »'
          expose:
            items_per_page_label: 'العناصر لكل صفحة'
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة تعيين'
          exposed_sorts_label: 'فرز حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      filters:
        state:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        translator:
          expose:
            label: المزود
  page_1:
    display_title: الصفحة
