<?php

use Drupal\entity_browser\Element\EntityBrowserElement;

/**
 * Implements hook_install().
 */
function test_c0a74801_install() {
  entity_get_form_display('node', 'page', 'default')
    ->setComponent('field_multi_image', [
      'type' => 'entity_browser_file',
      'settings' => [
        'entity_browser' => 'image_browser',
        'field_widget_edit' => TRUE,
        'field_widget_remove' => TRUE,
        'view_mode' => 'default',
        'preview_image_style' => 'thumbnail',
        'open' => TRUE,
        'selection_mode' => EntityBrowserElement::SELECTION_MODE_APPEND,
      ],
      'region' => 'content',
    ])
    ->save();
}

/**
 * Implements hook_uninstall().
 */
function test_c0a74801_uninstall() {
  // entity_load('field_config', 'node.page.field_multi_image')->delete();
  // entity_load('field_storage_config', 'node.field_multi_image')->delete();
}
