elements: |
  report_confirm_non_emergency:
    '#title': 'Mi atapwanapwan, áfeiengaw ngeni manawen aramas pwokiten mi wor ién mi feiengaw iká mi wor eew kkar iei?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Kese mwochen kopwene kaúnó ómw ammasowa eei taropween ammasow kosapw pwan chiwen niwiniti ómw kopwe kékkééri 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Fini menni nein ekkena memmeef pwe kopwe tongeni sópwosópwenó.</strong></p>'
  markup:
    '#markup': '<p><em><strong>Nupwen aa chóó watte chóón kékkéénong nón eew ier, iei minne ekkewe chóón angaangen apéchékkúna annúk (law enforcement) rese chiwen tawengeni eár repwe pénúweni meinisin chóón kékkéénong fáániten pwopwun ese-atapwanapwan. Ekkewe Chóón Chosa repwe wisen chosaani meinisin sakkopaaten kkar mi neoto sen i kapúngún anapi/nikachopwuchopw, iwe ién kewe re atai annúk repwe pwúsin angei chappan tipisin eár atai annúk.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Kese mwochen kopwene esineto ian ke nómw ian nupwen ómw rongorong ngeni ékúrangen anapi/nikachopwuchopw'
    '#location_address__description': 'Áweewe ren, ian address in ian ewe imwomw ewe ee nómw ian'
    '#unit_number__title': 'Nampaan ewe Unit'
    '#location_city__title': 'Itan ewe Sóópw'
    '#location_state__title': 'Itan ewe Fénú'
    '#location_zip__title': 'Nampaan ewe Zip Code'
  report_confirm_known_location:
    '#title': 'Een mi sinei ewe address áwenewenan ewe neeni aa wor kapúngún anapi ian?'
  report_incident_location:
    '#title': 'Kinikinin ewe Neeni'
  report_location:
    '#title': 'Kinikinin ewe Neeni'
    '#location_search__title': 'Kútten ewe Neeni'
    '#location_search__description': 'Kopwe kútta ewe map ngeni ewe kinikinin neeni iká address, ekkewe anen tarakú me itifengen, park, iká community center. Iká kopwene néúnéú ena map ómw kopwe tiki (click) wóón ena kinikinin neeni iká address.'
    '#location_details__title': 'Tichchikin ewe Neeni'
    '#location_details__description': 'Kese mwochen kopwene ngeni ekkóóch tichchikin pworóus eán epwe ánisi kich ach sipwe kúna ewe neeni ka esinesineto wóón'
  report_date:
    '#title': 'Ráánin ewe Kkar/Nikachopwuchopw'
  report_time:
    '#title': 'Áreere Kunók Fite aa Ffis ewe Kkar/Nikachopwuchopw'
  report_incident_description:
    '#title': 'Esineto met sókkun tichchikin pworóus epwe ánisi ne ánikiniki ewe kkar/nikachopwuchopw'
    '#description': '<p>Áweewe ren: énúwen ewe imw, itan ewe souimw, tarakkú sein ewe imw, pwan video iká ekkóóch sókkun kachiton ewe kkar/nikachopwuchopw atun eán ewe ffis. Iká epwe tufich, emén aramas epwe kékkééruk pwún epwe áiti ngonuk ifa ussun ómw kopwe atouranong ekkewe sasing me video met ewe ee ffis.</p>'
  section_contact:
    '#title': 'Ifa Tichchikin Pworóusomw Ren Ach Sipwe Tikeruk'
    '#description': '<p>Kese mwochen kopwe makketiw: Pwokiten mi nafangaw chóón angaang, KOSAPW áwitiwiti epwe wor pénúwen ómw eei report.</p>'
  contact_name:
    '#title': 'Itomw'
  contact_email:
    '#title': 'Ómw Email'
    '#description': '<p>Sipwe áeá ómw ena email ren ach sipwe anúkúnúkúúw noumw eei taropwe ka wanong nón eei neeni.</p>'
  contact_phone:
    '#title': 'Nampaan Phone'
  section_confidentiality:
    '#title': 'Amwónómwónenóón Pworóus'
  confidentiality_waiver:
    '#title': 'Kamwórenóón Manamanen Annúkún Mettóóch Epwe Amwónómwónenó'
    '#description': '<p>Annúkún eei Mwuun mi pesei pwún epwe amwónómwónenó tichchikin pworóusomw fáánitan epwe apwénúwetá masowen ómw eei tingór. Ewe Mwuun epwe achocho ngeni eán epwe amwónómwónaanó tichchikin pworóus een mi aworaato pwún esapw mecheres ngeni ekkóóch aramas eár repwe angei mwááni nge ese wor mwumwuutá senuk ussun mi pesepes fáán pwúngún annúkún mwuun <a href="/attorney/oregon-public-records-law">Oregon Fáánitan Isóisen Tichchikin Pworóusan Aramas</a>. Iká een mi mwochen epwe kamwórenó manamanen eei annúk mi pesei tichchikin pworóus epwe amwónómwónenó, kese mwochen fini menni meefiomw ena me nein ekkewe aa makketiw faan.</p>'
    '#options':
      'I do not waive confidentiality': 'Úse mwutaatá epwe kamwórenó manamanen ewe annúkún epwe amwónómwónenó tichchikin pworóusan aramas.'
      'I waive confidentiality': 'Úwa finaatá pwe epwe kamwórenó manamanen ewe annúkún eán epwe amwónómwónenó tichchikin pworóusan aramas.'
settings:
  confirmation_title: 'Kinisou ngonuk ren ómw ka atouranong noumw taropween kapasen ótuttur ren tipengawen neetip!'
  confirmation_message: '<p>Sia angei ómw ewe report (aa nampaani [webform_submission:values:report_ticket_id]). &nbsp;</p><p>Nupwen aa chóó watte chóón kékkéénong nón eew ier, iei minne ekkewe chóón angaangen apéchékkúna annúk (law enforcement) rese chiwen tawengeni eár repwe pénúweni meinisin chóón kékkéénong fáániten pwopwun ese-atapwanapwan. Inamwo iká ese pwúsin wor chóón angaang áwenewen ngeni ekkewe kapasen ótuttur fáánitan anapi/nikachopwuchopw, nge kich mi tinikkeni ach sipwe apéchékkúna ekkewe peekin annúk eán epwe Aúkaanó Ese Mwumwuutá Epwe Wor Anapi/Nikachopwuchopw. ESAPW wor ién epwe kékkééruk sefáán fáániten eei report.</p><p>Ekkewe Chóón Chosa repwe wisen chosaani meinisin sakkopaaten kkar mi neoto sen i kapúngún anapi/nikachopwuchopw, iwe ién kewe re atai annúk repwe pwúsin angei chappan tipisin eár atai annúk.</p><p>Iká pwe epwe wor chóón feiengaw iká epwe met epwe kkar, kopwe kékkééri 911.&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>Kinisou ngonuk ren ómw ka atouranong noumw taropween kapasen ótuttur ren tipengawen neetip!</h2><p>Sia angei ómw ewe report (aa nampaani [webform_submission:values:report_ticket_id]). &nbsp;</p><p>Nupwen aa chóó watte chóón kékkéénong nón eew ier, iei minne ekkewe chóón angaangen apéchékkúna annúk (law enforcement) rese chiwen tawengeni eár repwe pénúweni meinisin chóón kékkéénong fáániten pwopwun ese-atapwanapwan. Inamwo iká ese pwúsin wor chóón angaang áwenewen ngeni ekkewe kapasen ótuttur fáánitan anapi/nikachopwuchopw, nge kich mi tinikkeni ach sipwe apéchékkúna ekkewe peekin annúk eán epwe Aúkaanó Ese Mwumwuutá Epwe Wor Anapi/Nikachopwuchopw. ESAPW wor ién epwe kékkééruk sefáán fáániten eei report.</p><p>Ekkewe Chóón Chosa repwe wisen chosaani meinisin sakkopaaten kkar mi neoto sen i kapúngún anapi/nikachopwuchopw, iwe ién kewe re atai annúk repwe pwúsin angei chappan tipisin eár atai annúk.</p><p>Iká pwe epwe wor chóón feiengaw iká epwe met epwe kkar, kopwe kékkééri 911.&nbsp;</p>'
