<?php

use Drupal\node\Entity\Node;

// Attach the portland_news.js library to news nodes.
function portland_news_page_attachments(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() === 'entity.node.canonical') {
    $node = $route_match->getParameter('node');
    if ($node instanceof Node && $node->bundle() === 'news') {
      $attachments['#attached']['library'][] = 'portland_news/portland_news';
    }
  }
}
