display:
  default:
    display_title: 默认
    display_options:
      fields:
        usage_entity_type:
          label: 项类型
      pager:
        options:
          tags:
            next: '下一个 ›'
            previous: '‹ 上一个'
            first: '« 首页'
            last: '末页 »'
      arguments:
        asset_id:
          exception:
            title: 全部
