display:
  default:
    display_title: 默认
    display_options:
      fields:
        file_name:
          label: 名称
        asset_type:
          label: 类型
      pager:
        options:
          tags:
            next: '下一个 ›'
            previous: '‹ 上一个'
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
