display:
  default:
    display_title: 默认
    display_options:
      fields:
        archive_path:
          label: 文件地址
        file_name:
          label: 名称
        asset_type:
          label: 类型
        status_badge:
          label: 状态
        warnings:
          admin_label: 警告
          label: 警告
        operations:
          admin_label: 操作
          label: 操作
      pager:
        options:
          tags:
            next: '下一个 ›'
            previous: '‹ 上一个'
            first: '« 首页'
            last: '末页 »'
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      exposed_form:
        options:
          submit_button: 应用
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
          text_input_required: 选中任意的过滤器并点击“应用”查看结果
          bef:
            general:
              secondary_label: 高级选项
      filters:
        status:
          expose:
            label: 状态
          group_info:
            label: 状态
            group_items:
              1:
                title: 已排入队列
        asset_type:
          group_info:
            group_items:
              1:
                title: 文件
        archive_reason:
          group_info:
            group_items:
              1:
                title: 引用
              4:
                title: 其它
