display:
  default:
    display_title: 默认
    display_options:
      fields:
        source_entity_type:
          label: 项类型
        source_entity_id:
          label: 实体ID
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 每页条目数
            items_per_page_options_all_label: '- 全部 -'
            offset_label: 偏移量
      arguments:
        asset_id:
          exception:
            title: 全部
