title: 举报歧视
elements: |
  report_discrimination:
    '#title': 您想就违反您的权利和歧视您的纽约市计划、员工或承包商采取的纽约市政策或行动提出投诉吗？
    '#options':
      'Yes': 是的，我想举报歧视
      'No': '不，但我想申请 ADA 住宿'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>下一步</h2><p>请通过本市的<a href="/311/ada-request">ADA 住宿</a>服务提出请求。您也可以拨打<a href="tel:+1-503-823-4000">503-823-4000</a>或通过俄勒冈中继服务 TTY： <a href="tel:711">711</a>联系我们。工作人员可在周一至周五上午 8 点至下午 5 点提供帮助</p></div>'
  report_how_to_complete:
    '#title': 您希望如何完成您的请求或报告？
    '#options':
      'Call us': 给我们打电话
      'Continue online': 继续在线
  confidentiality_waiver:
    '#title': 保密豁免
    '#description': '<p>为了满足您的要求，纽约市的政策是对您在此表格中提供的信息保密。如果有人要求根据俄勒冈州<a href="/attorney/oregon-public-records-law" data-renderer-mark="true">公共记录法</a>将您的信息作为公共记录发布，本市还将尝试对您的信息保密。如果您希望放弃此保密性，请在下方选择该选项。</p>'
    '#options':
      'I do not waive confidentiality.': 我<em>不</em>放弃保密。
      'I choose to waive confidentiality.': 我选择放弃保密。
  report_who:
    '#title': 您要为谁提出此申请或投诉？
    '#options':
      Myself: 我本人
      'Someone else': 其他人
      'Neither of these apply to me': 两者都不适用于我
  report_who_neither_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Next Steps</h2><p>Completing this form starts an investigatory and potentially legal process. It is intended to be used by individuals or on behalf of individuals that believe they have been discriminated against.</p><p>If you have a concern or are attempting to point out a condition in the city that may be intentionally or unintentionally leading to the discrimination of a protected class, please use our <a href="/help/contact-elected-official">Contact an elected official form.</a></p></div>'
  report_on_behalf_of_permission:
    '#title': 您在提出此投诉之前，是否已获得他们的许可？
  report_on_behalf_of_name:
    '#title': 遭受歧视的个人或团体的姓名/名称是什么？
  report_third_party_relationship:
    '#title': 您与他们是什么关系，为什么要代表第三方提出投诉？
  report_on_behalf_of_permission_text_stop:
    '#markup': '<h2><span style="font-family:&quot;MS Gothic&quot;;">下一步</span></h2><p>填写此表格将启动调查并有可能启动法律程序。此表格可供认为自己受到了直接歧视的个人或团体使用。</p><p>如果您有顾虑或试图指出市政府可能有意或无意引导了受保护群体遭受歧视的情况，请使用我们的联系民选官员表格。</p>'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>下一步</h2><p>请通过俄勒冈中继服务致电 311、 <a href="tel:+15038234000">(503) 823-4000</a>或<a href="tel:711">711</a>联系我们获取 TTY。工作人员的工作时间为周一至周五上午 8:00 至下午 5:00，联邦节假日除外。</p></div>'
  report_discrimination_basis:
    '#title': 我相信我所经历的歧视是基于...
    '#description': '<p>（检查所有适用）</p>'
  report_discrimination_date:
    '#title': 事件发生的时间？
  report_location:
    '#location_search__title': 事件发生的地点？
    '#place_name__title': 地点详情和名称
    '#location_details__title': '请提供其他任何可能有助于我们找到您所举报的地点的详细信息，包括该地点是否有名称（例如公共建筑) 。'
  report_discrimination_bureau_office_etc:
    '#title': 请提供与歧视相关的市局、办公室、员工、事件或计划的名称
  report_discrimination_description:
    '#title': 用你自己的话描述所谓的歧视。
    '#description': '<p>请解释发生了什么；谁参与了；哪些政策、计划或活动具有歧视性（如果适用）；为什么你相信它会发生，以及你是如何受到歧视的。为保护您的隐私，请勿包含任何个人或健康相关信息。</p>'
  report_discrimination_witnesses:
    '#title': 有歧视的目击者吗？
  report_discrimination_witnesses_contact_known:
    '#title': 您知道他们的姓名和电话号码或电子邮件地址吗？
    '#description': '<p>只有在必要时才会联系证人以调查您的索赔。如果被联系，证人可以选择是否要参与调查过程。</p>'
  report_discrimination_witness_1_name:
    '#title': 第一证人姓名
  report_discrimination_witness_1_phone:
    '#title': 第一见证人电话
  report_discrimination_witness_1_email:
    '#title': 第一证人电子邮件
  report_discrimination_add_witness:
    '#title': 添加另一个见证人？
    '#options':
      'Add another witness': 添加另一个见证人
  report_discrimination_witness_2_name:
    '#title': 第二证人姓名
  report_discrimination_witness_2_phone:
    '#title': 第二个见证人电话
  report_discrimination_witness_2_email:
    '#title': 第二证人电子邮件
  report_discrimination_file_upload:
    '#title': 如果合适，请附上与您的投诉相关的任何照片或其他材料。
  report_discrimination_desired_outcome:
    '#title': 您希望看到采取什么类型的行动或解决方案？
  report_discrimination_filed_complaint_other:
    '#title': 您是否向任何其他联邦、州或地方机构或在任何联邦或州法院提出投诉？
    '#description': '<p>您有权向任何机构或法院提交文件。向其他机构或法院提出投诉并不妨碍您向波特兰市提出投诉。在某些情况下，机构将进行协调以确保适当的机构或法院对投诉进行调查。</p>'
    '#options':
      'Yes': 是的
      'No': 不
      'Prefer not to answer': 不想回答
  report_discrimination_filed_complaint_other_agency:
    '#title': 哪个机构或法院？
  report_agency_contact_markup:
    '#markup': '<p>如果您已向其他机构或法院提出投诉，请提供受理投诉的任何联系人或代表的姓名和电话号码或电子邮件（如果有) 。</p>'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 机构或法院联系人
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 机构或法院联系电话
  report_legal_representative_name:
    '#title': 如果有，请提供您的法务代表的姓名。
  report_legal_representative_contact_number:
    '#title': 如果有，请提供您的法务代表的联系信息。
  contact_name:
    '#title': 你的名字
  contact_email:
    '#title': 电子邮件
    '#description': '<p>我们将使用您的电子邮件确认您的提交。</p>'
  contact_phone:
    '#title': 电话
  contact_preferred_method:
    '#title': 如果需要，您希望我们通过电话或电子邮件与您联系吗？
    '#options':
      Phone: 电话
      Email: 电子邮件
  contact_interpreter:
    '#title': 你是否需要翻译员？
    '#options':
      'No': 不
      'Yes, VRI (Video Remote Interpretation)': 是的，VRI（视频远程口译）
      'Yes, Oregon Relay Service': 是的，俄勒冈中继服务
      'Yes, language interpreter': 是的，语言翻译
  contact_language:
    '#title': 哪种语言？
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>投诉人确认</strong></p><p>通过提交此表格，我确认 (1) 我已阅读、理解并接受<a href="/code/23">跟踪和调查民权投诉的程序条款，</a>以及 (2) 据我所知，我在此表格中提供的信息是真实的。</p>'
  complainant_acknowledgement_agree:
    '#title': 我同意
  actions:
    '#title': 提交按钮
    '#submit__label': 提交
  report_ticket_id:
    '#title': '报告工单 ID'
settings:
  confirmation_title: ''
  confirmation_message: ''
handlers:
  zendesk_new_ticket:
    label: 'Zendesk 新票'
    notes: '创建一个新的歧视投诉单并将其分配给 311：ADA 和歧视组。'
