title: ADA住宿要求
elements: |
  request_how:
    '#title': 你想如何提出你的要求？
    '#options':
      'I would like to call the City': '我想通过电话或 TTY 联系市政府。'
      'I will continue with the online form': 我将继续使用在线表格
  markup_continue:
    '#markup': '<p class="mt-5"><strong>请做出选择以继续。</strong></p>'
  request_call_city_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>下一步</h2><p>请通过俄勒冈中继服务致电<a href="tel:311">311</a> 、 <a href="tel:+15038234000">(503) 823-4000</a>或<a href="tel:711">711</a>联系我们获取 TTY。工作人员的工作时间为周一至周五上午 8:00 至下午 5:00，联邦节假日除外。</p></div>'
  request_who:
    '#title': 您是代表谁提出此请求或投诉？
    '#options':
      Myself: 我
      'Someone else': 他人
      'Neither of these apply to me': 这两者都不适用于我。
  request_who_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>信息</h2><p>勾选此选项，即表示我确认本人患有属于《美国残疾人法案》（Americans with Disabilities Act）涵盖范围内的残疾，且据我所知及所信，我在本表格中提供的信息均真实无误。</p></div>'
  request_someone_else_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>信息</h2><p>勾选此选项，即表示我确认：我代其提出此项请求或投诉的人士患有属于《美国残疾人法案》涵盖范围内的残疾；且据我所知及所信，我在本表格中提供的信息均真实无误。</p></div>'
  request_who_neither_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>信息</h2><p>如果您希望报告您认为可能影响或威胁公众（尤其是残障人士）的观察事项、问题或隐患，请选择此选项。如需协助，请致电 <a href="tel:311">311</a> 或发送电子邮件至 <a href="mailto:311@portlandoregon.gov">311@portlandoregon.gov</a> 联系我们。</p></div>'
  request_on_behalf_of_permission:
    '#title': 您是否已获得他们的许可来提交此投诉？或者，您是否具有允许您代表他们进行投诉的法律关系？
  request_on_behalf_of_name:
    '#title': 他们叫什么名字？
  request_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>后续步骤</h2><p>请在提交此表格前，征得他们的许可。</p></div>'
  container_confidentiality:
    '#title': 保密
  confidentiality_waiver:
    '#title': 保密豁免
    '#description': '<p>纽约市的政策是对您在此表格中提供的信息保密。您的信息将被保密，除非您选中证明您愿意放弃保密的复选框。</p>'
    '#options':
      'I do not waive confidentiality': 我<em>不</em>放弃保密。
      'I waive confidentiality': 我选择放弃保密。
  request_what:
    '#title': 我想请求市...
    '#options':
      event_accommodations: 为城市活动、事件或计划提供住宿
      parks_activity_registration: '为波特兰公园与娱乐局（Portland Parks & Recreation）活动的注册及账户设置流程提供便利协助。'
      city_materials: 以我可以访问的格式提供城市材料
      app_accessibility: 修复城市应用或网站的无障碍问题
      remove_barrier: 移除障碍物或让我更容易进入街道、人行道、小径、公园或其他城市拥有的空间（例如移除人行道上的障碍物、添加人行横道或改进标志）
      change_policy: 更改或修改政策或程序（例如，允许残疾社区成员提早参加活动，允许同伴参加课程或活动）
    '#other__option_label': 还有什么...
    '#other__description': 请描述您的要求。为保护您的隐私，请勿包含任何个人或健康相关信息。
  request_parks_assistance:
    '#title': 您需要哪种类型的协助？
    '#options':
      'Setting up my ActiveNet account (the system Portland Parks and Recreation uses for class/recreation registrations)': '设置我的 ActiveNet 账户（波特兰公园与娱乐局用于课程及娱乐活动注册的系统）'
      'Instructions and resources to help me get signed up for upcoming recreation activities': 协助我报名参加近期文娱活动的指南与资源
  container_materials:
    '#title': 索取材料
  request_materials_type:
    '#title': 你要的材料是...
    '#options':
      website: 在城市的网站上？
      event: 对于特定的事件或活动？
      printed: 没有在线提供的印刷文件？
    '#other__option_label': 还有什么...
    '#other__description': 请描述材料。
  request_materials_url:
    '#title': 材料所在页面的网址（URL）是什么？
  request_materials_description:
    '#title': 文件的名称和/或描述
  page_you_last_viewed:
    '#title': 您上次浏览的页面
  continue_button:
    '#markup': '<p><a class="button button--primary" href="/feedback?page_you_last_viewed=[server:HTTP_REFERER]&amp;subject=Fix%20an%20accessibility%20issue%20with%20a%20City%20app%20or%20website" aria-label="继续报告城市应用程序或网站的无障碍问题">继续报告应用或网站问题</a></p>'
  container_event:
    '#title': 活动详情
  request_event_name:
    '#title': 活动、事件或计划的名称
  request_event_date:
    '#title': 活动日期
  request_event_location:
    '#title': 活动地点
  request_event_bureau_sponsor:
    '#title': 活动主持人
    '#description': '<p>如果您知道，请指定主办该活动的市局、办公室、计划、项目或民选官员。</p>'
  request_event_url:
    '#title': 活动详情网址
    '#description': '<p>如果知道，请复制并粘贴活动、计划或材料网站的 URL 地址。</p>'
  container_event_accommodations:
    '#title': 活动住宿
  request_event_accommodations_type:
    '#title': 您要求什么类型的住宿？
    '#description': '<p>检查所有适用。</p>'
    '#options':
      accessible_parking: 无障碍停车场
      accessible_entrance: 活动的无障碍入口和通往洗手间的路线
      communication_aids: 沟通辅助
      accessible_materials: 可访问格式的材料
    '#other__option_label': 还有什么...
    '#other__description': 请描述您的要求。为保护您的隐私，请勿包含任何个人或健康相关信息。
  request_event_communiation_aids_type:
    '#title': 您更喜欢哪种类型的通讯工具？
    '#options':
      captioning: 字幕
      listening_device: 助听器
      interpretation_asl: 'ASL 中的解释'
      interpretation_other: 用另一种手语或触觉语言进行翻译
    '#other__option_label': 还有什么...
    '#other__description': 请描述您的要求。为保护您的隐私，请勿包含任何个人或健康相关信息。
  request_event_materials_format:
    '#title': 您更喜欢哪种形式的活动材料？
    '#options':
      accessble_word_doc: '可访问的电子文档 (Microsoft Word)'
      accessible_pdf: '可访问的电子文档 (PDF)'
      large_print: 大字纸
      braille: 盲文
    '#other__option_label': 还有什么...
    '#other__description': 请描述您的要求。为保护您的隐私，请勿包含任何个人或健康相关信息。
  container_remove_barrier:
    '#title': 移除障碍
  request_barrier_type:
    '#title': 您要报告什么类型的问题？我们如何让您更轻松地访问？
    '#options':
      barrier: '障碍物 - 有障碍物、障碍物或阻碍进入的东西'
      parking: '停车 - 没有无障碍停车位，或现有停车位有问题'
      signage: '标志 - 没有标志，或标志不清楚'
    '#other__option_label': 还有什么...
    '#other__description': 请描述。
  report_location:
    '#title': 障碍或问题的位置
    '#location_search__title': 位置搜索
    '#location_map__title': 位置图
    '#suggestions_modal__title': 建议
    '#status_modal__title': 状态指示灯
    '#location_address__title': 地址或十字路口
    '#location_lat__title': 纬度
    '#location_lon__title': 经度
    '#place_name__title': 地名
    '#location_details__title': 位置详情
    '#location_asset_id__title': '资产 ID'
  report_barrier_description:
    '#title': 问题描述
    '#description': '<p>请详细描述问题。我们如何才能更容易地访问您的城市？为保护您的隐私，请勿包含任何个人或健康相关信息。</p>'
  container_change_policy:
    '#title': 变更政策
  report_policy_request:
    '#title': 你有什么要求？
    '#description': '<p>请描述您要求的政策或程序变更。为保护您的隐私，请勿包含任何个人或健康相关信息。</p>'
  section_contact:
    '#title': 联系信息
  contact_name:
    '#title': 你的名字
  contact_email:
    '#title': 你的邮件
    '#description': '<p>我们将使用您的电子邮件回复您的反馈或请求。</p>'
    '#pattern_error': '请输入格式正确的电子邮件地址，例如 myname@example.com。'
  contact_phone:
    '#title': 电话
  contact_phone_assistance_type:
    '#title': 如果您需要电话帮助，请选择一个选项
    '#options':
      vri: VRI
      relay: '俄勒冈中继服务 (TTY)'
      interpreter: 口译员
      none: 以上都不是
  report_ticket_id:
    '#title': '报告工单 ID'
  computed_location_address:
    '#title': 计算位置地址
  computed_location_latlon:
    '#title': 计算定位
  actions:
    '#title': 提交按钮
    '#submit__label': 提交
settings:
  confirmation_title: 感谢您提交您的请求！
  confirmation_message: '<p>您的请求已收到，应在 48 小时内与您联系。</p>'
handlers:
  zendesk_new_ticket:
    label: 'Zendesk 新票'
    notes: '创建一个新的 ADA 住宿请求票并将其分配给 311 组。'
