title: 网站反馈
description: '<p>此网络表单用于收集用户和编辑的网站反馈。</p>'
elements: |
  subject:
    '#title': 反馈类型
    '#options':
      "I cannot find what I'm looking for": 我找不到我要找的东西
      'I have a question': 我有个问题
      'The page looks broken': 页面看起来坏了
      'The information looks incorrect': 信息看起来不正确
      'Contact an elected official with feedback': 联系民选官员并提供反馈
      'Fix an accessibility issue with a City app or website': 修复城市应用或网站的无障碍问题
    '#empty_option': '-  选择  -'
  link_to_contact_elected:
    '#markup': '<div class="alert alert--info next-steps"><h2>下一步</h2><p>请使用<a href="/help/contact-elected-official">联系人的官方表格</a>发送您的反馈或请求会议。</p></div>'
  feedback:
    '#title': 细节
    '#description': '<p>请具体说明，以便我们更好地为您提供帮助。</p>'
  your_name:
    '#title': 你的名字
  email_address:
    '#title': 你的邮件
  page_you_last_viewed:
    '#title': 您上次查看的页面
    '#description': '<p>如果您想在不同的页面上发表评论，您可以更改此地址。</p>'
    '#default_value': '[服务器：HTTP_REFERER]'
  public_records_statement:
    '#markup': '<p>根据俄勒冈州<a href="/attorney/oregon-public-records-law" data-renderer-mark="true">公共记录法</a>，您在本表格中提供的信息被视为公共记录，可应要求提供给公众。</p>'
  support_agent_use_only:
    '#title__title': ''
  actions:
    '#title': 提交按钮
  ip_address:
    '#title': IP地址
settings:
  form_close_message: '<p>我们的反馈表暂时关闭。如果您对我们如何改进此页面有反馈或建议，请发送电子邮件至 powr@portlandoregon.gov 发送电子邮件至网络团队。</p>'
  confirmation_message: '<h2>感谢您提交反馈，我们感谢您的帮助！</h2><p>您应该很快就会收到一封电子邮件确认。您可以回复该电子邮件以向您的反馈添加其他信息或评论。<br><br>名称：[webform_submission:values:your_name]<br><br>电子邮件：[webform_submission:values:email_address]<br><br>反馈类型：[webform_submission:values:subject]<br><br>上次查看的页面： <a href="[webform_submission:values:page_you_last_viewed]">[webform_submission:values:page_you_last_viewed]</a><br><br>反馈：[webform_submission:values:feedback]</p>'
handlers:
  submit_report_to_311:
    label: 向311提交报告
    notes: ''
    settings:
      from_name: ''
      body: '<p>主题：[webform_submission:values:subject]</p><p>反馈：[webform_submission:values:feedback]</p><p>名称：[webform_submission:values:your_name]</p><p>电子邮件：[webform_submission:values:email_address]</p><p>上次查看的页面：[webform_submission:values:page_you_last_viewed]</p><p>提交时间：[webform_submission:created]</p><p>用户代理：[服务器：HTTP_USER_AGENT]</p><p>[webform_submission:values:agent_summary]</p>'
  submit_report_to_website_support:
    label: 向网站支持提交报告
    notes: ''
    settings:
      from_name: ''
      body: '<p>主题：[webform_submission:values:subject]</p><p>反馈：[webform_submission:values:feedback]</p><p>名称：[webform_submission:values:your_name]</p><p>电子邮件：[webform_submission:values:email_address]</p><p>上次查看的页面：[webform_submission:values:page_you_last_viewed]</p><p>提交时间：[webform_submission:created]</p><p>用户代理：[服务器：HTTP_USER_AGENT]<br><br>[webform_submission:values:agent_summary]</p>'
