elements: |
  report_confirm_non_emergency:
    '#title': 這是否為有人員受傷或有火災發生的緊急危及生命事件？
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>請停止填寫此表單並撥打 911。</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>請選擇以繼續</strong></p>'
  markup:
    '#markup': '<p><em><strong>在每年案件量較多的時段，執法部門無足夠資源來回應所有非緊急案件通報。火災調查人員將調查所有煙火相關火災，違規者被追究責任。</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 請分享您聽到煙火施放時的所在位置
    '#location_address__description': 例如：您的住家地址
    '#unit_number__title': 單位編號
    '#location_city__title': 城市
    '#location_state__title': 州
    '#location_zip__title': 郵遞區號
  report_confirm_known_location:
    '#title': 您是否知道煙火施放的地點？
  report_incident_location:
    '#title': 事件發生地點
  report_location:
    '#title': 事件發生地點
    '#location_search__title': 搜尋地點
    '#location_search__description': '在地圖上搜尋地址、路口、公園或社區中心。或使用地圖點選地點。'
    '#location_details__title': 地點詳情
    '#location_details__description': '請提供任何可能有助於我們定位您所通報地點的細節。'
  report_date:
    '#title': 事件日期
  report_time:
    '#title': 事件發生的大約時間
  report_incident_description:
    '#title': 請提供任何有助於了解事件的描述
    '#description': '<p>例如：房屋顏色、屋主資訊、相關車輛，或您是否持有事件影片或其他媒體資料。如有需要，相關人員將與您聯絡，說明如何提交照片或影片。</p>'
  section_contact:
    '#title': 您的聯絡資訊
    '#description': '<p>請注意：由於資源有限，請勿預期會收到此通報的回覆。</p>'
  contact_name:
    '#title': 姓名
  contact_email:
    '#title': 電子郵件
    '#description': '<p>我們將使用您的電子郵件確認您已送交完成。</p>'
  contact_phone:
    '#title': 電話
  section_confidentiality:
    '#title': 保密聲明
  confidentiality_waiver:
    '#title': 放棄保密聲明
    '#description': '<p>依本市政策規定，您在此表單中提供的資訊將予以保密，以便處理您的請求。若有人根據<a href="/attorney/oregon-public-records-law">《奧勒岡州公共記錄法》</a> (Oregon Public Records Law) 請求公開相關記錄，本市亦會盡力為您的資訊保密。若您希望放棄此保密權利，請選擇下方選項。&nbsp;</p>'
    '#options':
      'I do not waive confidentiality': 我不放棄保密權利。
      'I waive confidentiality': 我選擇放棄保密權利。
settings:
  confirmation_title: 感謝您提交投訴！
  confirmation_message: '<p>我們已收到您的報告（編號：#[webform_submission:values:report_ticket_id]）。</p><p>在每年案件量較多的時段，執法部門無足夠資源來回應所有非緊急案件通報。儘管目前無足夠資源來回應多數煙火相關投訴，但我們正在收集資訊，以持續推動遵守煙火禁令。請勿預期會有人致電回覆此通報。</p><p>火災調查人員將調查所有煙火相關火災，違規者被追究責任。</p><p>若煙火情況涉及人員受傷或有物體起火，請撥打 911。&nbsp;</p>'
handlers:
  email:
    settings:
      body: '<h2>感謝您提交投訴！</h2><p>我們已收到您的報告（編號：#[webform_submission:values:report_ticket_id]）。</p><p>在每年案件量較多的時段，執法部門無足夠資源來回應所有非緊急案件通報。儘管目前無足夠資源來回應多數煙火相關投訴，但我們正在收集資訊，以持續推動遵守煙火禁令。請勿預期會有人致電回覆此通報。</p><p>火災調查人員將調查所有煙火相關火災，違規者被追究責任。</p><p>若煙火情況涉及人員受傷或有物體起火，請撥打 911。&nbsp;</p>'
