display:
  default:
    display_options:
      fields:
        name:
          label: អ្នក​ប្រើ
        group_roles:
          label: តួនាទី​
        changed:
          label: បាន​ធ្វើ​បច្ចុប្បន្នភាព
      exposed_form:
        options:
          reset_button_label: កំណត់​ឡើង​វិញ
      arguments:
        gid:
          exception:
            title: ទាំងអស់
  page_1:
    display_title: ទំព័រ
