display:
  default:
    display_title: លំនាំដើម
    display_options:
      fields:
        file_name:
          label: ឈ្មោះ
        asset_type:
          label: ប្រភេទ
        status_badge:
          label: ស្ថានភាព
        operations:
          admin_label: ប្រតិបត្តិការ
          label: ប្រតិបត្តិការ
      exposed_form:
        options:
          reset_button_label: កំណត់​ឡើង​វិញ
          bef:
            general:
              secondary_label: ជម្រើសកម្រិតខ្ពស់
      filters:
        status:
          expose:
            label: ស្ថានភាព
          group_info:
            label: ស្ថានភាព
        archive_reason:
          group_info:
            group_items:
              4:
                title: ផ្សេងៗ
