display:
  default:
    display_title: លំនាំដើម
    display_options:
      fields:
        fid:
          label: លេខ​សម្គាល់​ឯកសារ
        asset_type:
          label: ប្រភេទ
        mime_type:
          label: ប្រភេទ
        filesize:
          label: ទំហំ
        source_type:
          label: ទីតាំង
        operations:
          label: ប្រតិបត្តិការ
      exposed_form:
        options:
          reset_button_label: កំណត់​ឡើង​វិញ
      filters:
        category:
          group_info:
            group_items:
              10:
                title: ផ្សេងៗ
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: ប្រភេទ
        source_type:
          label: ទីតាំង
