<?php

/**
 * Implements hook_preprocess_HOOK().
 *
 * Attaches glossary_term library to the body content field if it contains a glossary term link.
 */
function portland_glossary_preprocess_field__field_body_content(&$variables) {
  if (array_key_exists('#items', $variables['element'])) {
    /** @var \Drupal\Core\Field\FieldItemListInterface $items */
    $items = $variables['element']['#items'];
    if ($items->isEmpty()) return;

    $body_content = $items->first()->value;
    if (str_contains($body_content, 'data-entity-substitution="glossary_term"')) {
      $variables['#attached']['library'][] = 'portland_glossary/glossary_term';
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * For lack of a better place to put this, we modify the accordion behavior on PP&D pages using the new design.
 * - Collapse all rows by default.
 * - Only show expand all/collapse all starting at 3 rows.
 * TODO: Remove this if we decide to expand behavior to all pages.
 */
function portland_glossary_node_view(array &$build, \Drupal\node\Entity\Node $node, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode !== 'full') {
    return;
  }

  // Page must be using new design if Page subtype == Service or it has a parent page.
  if (($node->bundle() === 'page' && $node->field_page_type->target_id === "1032") || ($node->hasField('field_parent') && $node->field_parent->count() > 0)) {
    $build['#attached']['drupalSettings']['portland']['cloudyExpandAllAccordion']['minRows'] = 3;
  }
}
