adding:
  requirements:
    configuration_files:
      action: change_severity
      severity: ok
      reason: 'Ignored on local development environments.'
    redis:
      action: change_severity
      severity: ok
      reason: 'Ignored on local development environments.'
removing: {  }
