<?php

/**
 * @file
 * General functions and hook implementations.
 *
 * @see http://harvesthq.github.com/chosen/
 */

/**
 * Implements hook_library_info_alter().
 */
function chosen_lib_library_info_alter(array &$libraries, $module) {
  if ('chosen_lib' == $module) {
    if (isset($libraries['chosen'])) {
      // Set chosen library path.
      $chosen_js_path = _chosen_lib_get_chosen_path();
      $minified = file_exists($chosen_js_path . '/chosen.jquery.min.js');
      $chosen_js_path = '/' . $chosen_js_path;
      $chosen_js = $minified
        ? $chosen_js_path . '/chosen.jquery.min.js'
        : $chosen_js_path . '/chosen.jquery.js';
      $libraries['chosen']['js'][$chosen_js] = array(
        'minified' => $minified,
      );
      $chosen_css = $chosen_js_path . '/chosen.css';
      $libraries['chosen.css']['css']['component'][$chosen_css] = array();
    }
  }
}

/**
 * Get the location of the chosen library.
 *
 * @return string
 *   The location of the library, or FALSE if the library isn't installed.
 */
function _chosen_lib_get_chosen_path() {
  if (function_exists('libraries_get_path')) {
    return libraries_get_path('chosen');
  }

  // The following logic is taken from libraries_get_libraries()
  $searchdir = array();

  // Similar to 'modules' and 'themes' directories inside an installation
  // profile, installation profiles may want to place libraries into a
  // 'libraries' directory.
  $searchdir[] = 'profiles/' . drupal_get_profile() . '/libraries';

  // Always search libraries.
  $searchdir[] = 'libraries';

  // Also search sites/<domain>/*.
  $searchdir[] = \Drupal::service('site.path') . '/libraries';

  foreach ($searchdir as $dir) {
    if (file_exists($dir . '/chosen/chosen.jquery.min.js') || file_exists($dir . '/chosen/chosen.jquery.js')) {
      return $dir . '/chosen';
    }
  }

  return FALSE;
}
