display:
  default:
    display_options:
      title: 'Job items'
      fields:
        type:
          label: Uri
        source_language:
          label: 'Mula kay'
        target_language:
          label: 'Para kay'
        tags_count:
          label: 'Mga etiketa'
        operations:
          label: 'Mga operasyon'
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
  page_1:
    display_title: Pahina
    display_options:
      menu:
        title: 'Job items'
