display:
  default:
    display_options:
      fields:
        group_roles:
          label: 'Mga papel'
        changed:
          label: Nabago
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
      arguments:
        gid:
          exception:
            title: Lahat
  page_1:
    display_title: Pahina
