display:
  default:
    display_title: Pamantayan
    display_options:
      fields:
        fid:
          label: 'ID ng talaksan'
        asset_type:
          label: Uri
        mime_type:
          label: Uri
        operations:
          label: 'Mga operasyon'
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
