display:
  default:
    display_title: Pamantayan
    display_options:
      fields:
        file_name:
          label: Pangalan
        asset_type:
          label: Uri
        status_badge:
          label: Kalagayan
        operations:
          admin_label: 'Mga operasyon'
          label: 'Mga operasyon'
      exposed_form:
        options:
          reset_button_label: 'Ibalik sa pamantayan'
          bef:
            general:
              secondary_label: 'Mga abansadong pagpipilian'
      filters:
        status:
          expose:
            label: Kalagayan
          group_info:
            label: Kalagayan
