_core:
  default_config_hash: kli1Xws0l--Y-jy-9ZTGApFO_EFk9DMawoetjMk76Ro
always_save_userinfo: true
connect_existing_users: false
override_registration_settings: true
end_session_enabled: true
user_login_display: null
redirect_login: user
redirect_logout: ''
userinfo_mappings:
  timezone: zoneinfo
role_mappings: {  }
autostart_login: false
