_core:
  default_config_hash: 3U6sHS0xqnEGwbTJo7bLZCYbYwWFqKiNVhuE6FDgcN8
enabled_entities:
  block_content: true
  group: true
  media: true
  menu_link_content: true
  node: true
  relation: true
  taxonomy_term: true
disable_automatic_queueing: false
verbose_log: false
defaults:
  block_content:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  group:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  media:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  menu_link_content:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  node:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  relation:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
  taxonomy_term:
    age:
      id: age
      status: true
      settings:
        age: 6
    amount:
      id: amount
      status: true
      settings:
        amount: 3
