<?php
/*
 * @file
 * "Portland Address Autocomplete" provides address suggestions from PortlandMaps.
 * 
 */


function portland_address_complete_preprocess_input(&$variables) {
  $element = &$variables['element'];
  if( array_key_exists('#id', $element)) {
    // Match these IDs:
    // "edit-field-address-or-entrance-0-address-address-line1"
    // "edit-inline-entity-form-field-address-or-entrance-0-address-address-line1"
    if(preg_match('/edit(\-|\w)+field-address-or-entrance-(\d)+-address-address-line1/i', $element["#id"], $matches)) {
      $variables["attributes"]['list'] = 'addresslist';
      // Workaround for FireFox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1474137
      $variables["attributes"]['autocomplete'] = 'off';
    }
  }
}

// The Location edit form
function portland_address_complete_form_alter(&$form, &$form_state, $form_id) {
  if(array_key_exists("field_address_or_entrance", $form)) {
    // $form['field_address_or_entrance']['address']['address_line1']['#attributes']['list'] = 'address_list';
    // $form['address_list']['#markup'] = t('<datalist id="address_list"></datalist>');
    $form['#attached']['library'][] = 'portland_address_complete/portland_address_complete';
    $form['#attached']['drupalSettings']['portlandmaps_api_key'] = \Drupal::service('key.repository')->getKey('portlandmaps_api')->getKeyValue();
  }
}

// The location edit form embedded in entity browser
function portland_address_complete_inline_entity_form_entity_form_alter(&$form, &$form_state) {
  if(array_key_exists("field_address_or_entrance", $form)) {
    $form['#attached']['library'][] = 'portland_address_complete/portland_address_complete';
    $form['#attached']['drupalSettings']['portlandmaps_api_key'] = \Drupal::service('key.repository')->getKey('portlandmaps_api')->getKeyValue();
  }
}