display:
  default:
    display_title: 기본값
    display_options:
      fields:
        file_name:
          label: 이름
        asset_type:
          label: 종류
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
