display:
  default:
    display_title: 기본값
    display_options:
      fields:
        source_entity_type:
          label: '항목 종류'
        source_entity_id:
          label: '엔터티 ID'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      arguments:
        asset_id:
          exception:
            title: 전체
