display:
  default:
    display_title: 기본값
    display_options:
      fields:
        file_name:
          label: 이름
        asset_type:
          label: 종류
        status_badge:
          label: 상태
        warnings:
          admin_label: 경고
          label: 경고
        operations:
          admin_label: 작업
          label: 작업
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
          text_input_required: '필터를 선택하고 적용을 클릭하여 결과 확인'
          bef:
            general:
              secondary_label: '고급 선택사항'
      filters:
        status:
          expose:
            label: 상태
          group_info:
            label: 상태
            group_items:
              1:
                title: '큐에 배치됨'
        archive_reason:
          group_info:
            group_items:
              1:
                title: 참조
              4:
                title: 기타
