display:
  default:
    display_title: 기본값
    display_options:
      fields:
        fid:
          label: '파일 ID'
        asset_type:
          label: 종류
        mime_type:
          label: 종류
        filesize:
          label: '파일 크기'
        source_type:
          label: 위치
        operations:
          label: 작업
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
            first: '« 처음'
            last: '마지막 »'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      filters:
        category:
          group_info:
            group_items:
              10:
                title: 기타
  data_export_csv_inventory:
    display_options:
      fields:
        category:
          label: 카테고리
        source_type:
          label: 위치
