display:
  default:
    display_title: 기본값
    display_options:
      fields:
        usage_entity_type:
          label: '항목 종류'
        usage_field:
          label: 영역
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
            first: '« 처음'
            last: '마지막 »'
      arguments:
        asset_id:
          exception:
            title: 전체
