<?php

use \Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 * 
 * Performs the following:
 * - If a node revision is published, clear any user from the Reviewer field
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 * @return void
 */
function portland_moderation_helper_entity_presave(EntityInterface $entity)
{
  $type = $entity->getEntityTypeId();

  if ($type == "node") {
    _portland_moderation_helper_remove_reviewer_when_node_published($entity);
  }
}

function _portland_moderation_helper_remove_reviewer_when_node_published(EntityInterface $entity) {
  if (!isset($entity->field_reviewer) || $entity->moderation_state->value != "published") {
    return false;
  }
  // node is published, clear reviewer
  $entity->set('field_reviewer', null);
}