display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        usage_field:
          label: Sección
      pager:
        options:
          tags:
            next: 'Siguiente ›'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
      arguments:
        asset_id:
          exception:
            title: Todo(s)
