display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        archive_path:
          label: 'URL del archivo'
        file_name:
          label: Nombre
        asset_type:
          label: Tipo
        status_badge:
          label: Estado
        warnings:
          admin_label: Advertencias
          label: Advertencias
        operations:
          admin_label: Operaciones
          label: Operaciones
      pager:
        options:
          tags:
            next: 'Siguiente ›'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Seleccione cualquier filtro y pulse Aplicar para ver los resultados'
          bef:
            general:
              secondary_label: 'Opciones avanzadas'
      filters:
        status:
          expose:
            label: Estado
          group_info:
            label: Estado
            group_items:
              1:
                title: 'En cola'
        asset_type:
          group_info:
            group_items:
              1:
                title: Documentos
        archive_reason:
          group_info:
            group_items:
              1:
                title: Referencia
              4:
                title: Otro(s)
