display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        source_entity_id:
          label: 'ID de entidad'
        field_name:
          label: 'Nombre de campo'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      arguments:
        asset_id:
          exception:
            title: Todo(s)
