display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        file_name:
          label: Nombre
        asset_type:
          label: Tipo
      pager:
        options:
          tags:
            next: 'Siguiente ›'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
