display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        fid:
          label: 'ID del archivo'
        asset_type:
          label: Tipo
        file_path:
          label: 'URL del archivo'
        mime_type:
          label: Tipo
        filesize:
          label: Tamaño
        source_type:
          label: Ubicación
        operations:
          label: Operaciones
      pager:
        options:
          tags:
            next: 'Siguiente ›'
            previous: '‹ Anterior'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        category:
          group_info:
            group_items:
              10:
                title: Otro(s)
  data_export_csv_inventory:
    display_options:
      fields:
        file_path:
          label: 'URL del archivo'
        category:
          label: Categoría
        mime_type:
          label: 'Tipo MIME'
        source_type:
          label: Ubicación
        filesize_formatted:
          separator: ', '
        active_use_csv:
          separator: ', '
        used_in_csv:
          separator: ', '
