title: 'Solicitud de adaptación de la ADA'
elements: |
  request_how:
    '#title': '¿Cómo te gustaría hacer tu pedido?'
    '#options':
      'I would like to call the City': 'Me gustaría contactar a la Ciudad por teléfono o TTY.'
      'I will continue with the online form': 'Continuaré con el formulario en línea.'
  markup_continue:
    '#markup': '<p class="mt-5"><strong>Por favor, haga una selección para continuar.</strong></p>'
  request_call_city_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p>Llámenos al <a href="tel:311">311</a> , <a href="tel:+15038234000">(503) 823-4000</a> o al <a href="tel:711">711</a> para TTY a través del Servicio de retransmisión de Oregon. El personal está disponible de lunes a viernes de 8:00 am a 5:00 pm, excepto días festivos federales.</p></div>'
  request_who:
    '#title': '¿Para quién está realizando esta solicitud o queja?'
    '#options':
      Myself: 'Mí mismo'
      'Someone else': 'Alguien más'
      'Neither of these apply to me': 'Ninguno de estos se aplica a mí.'
  request_who_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Información</h2><p>Al seleccionar esta opción, certifico que tengo una discapacidad amparada por la Ley de Estadounidenses con Discapacidades (Americans with Disabilities Act) y que la información que proporciono en este formulario es verídica, a mi leal saber y entender.</p></div>'
  request_someone_else_myself_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Información</h2><p>Al seleccionar esta opción, certifico que la persona en cuyo nombre realizo esta solicitud o queja tiene una discapacidad amparada por la Ley de Estadounidenses con Discapacidades (Americans with Disabilities Act) y que la información que proporciono en este formulario es verídica, a mi leal saber y entender.</p></div>'
  request_who_neither_text:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Información</h2><p>Esta opción se utilizaría si desea reportar una observación, un problema o una inquietud que, a su juicio, pueda afectar o representar una amenaza para el público en general, especialmente para las personas con discapacidad. Por favor, contáctenos llamando al <a href="tel:311">311</a> o escribiendo a <a href="311@portlandoregon.gov">311@portlandoregon.gov</a> para recibir asistencia.</p></div>'
  request_on_behalf_of_permission:
    '#title': '¿Ha obtenido el permiso de ellos para presentar esta queja? ¿O tiene una relación legal que le permita presentar una queja en su nombre?'
  request_on_behalf_of_name:
    '#title': '¿Cómo se llaman?'
  request_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p>Por favor, obtenga su permiso antes de enviar este formulario.</p></div>'
  container_confidentiality:
    '#title': Confidencialidad
  confidentiality_waiver:
    '#title': 'Exención de confidencialidad'
    '#description': '<p>Es política de la ciudad mantener confidencial la información que proporcione en este formulario. Su información se mantendrá confidencial a menos que marque la casilla que certifique que desea renunciar a la confidencialidad.</p>'
    '#options':
      'I do not waive confidentiality': '<em>No</em> renuncio a la confidencialidad.'
      'I waive confidentiality': 'Elijo renunciar a la confidencialidad.'
  request_what:
    '#title': 'Me gustaría solicitar que la ciudad...'
    '#options':
      event_accommodations: 'Proporcionar alojamiento para una actividad, evento o programa de la Ciudad'
      parks_activity_registration: 'Proporcionar adaptaciones para el proceso de registro y la configuración de cuentas para las actividades de Portland Parks & Recreation.'
      city_materials: 'Proporcionar materiales de la Ciudad en un formato que sea accesible para mí'
      app_accessibility: 'Solucionar un problema de accesibilidad en una aplicación o sitio web de la ciudad'
      remove_barrier: 'Eliminar una barrera o facilitarme el acceso a una calle, acera, sendero, parque u otro espacio propiedad de la Ciudad (como eliminar una obstrucción en una acera, agregar cruces peatonales o mejorar la señalización)'
      change_policy: 'Cambiar o modificar una política o procedimiento (por ejemplo, permitir que los miembros de la comunidad con discapacidades ingresen temprano a un evento, permitir que un acompañante asista a una clase o actividad)'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor, describa su solicitud. No incluya información personal ni relacionada con la salud.'
  request_parks_assistance:
    '#title': '¿Qué tipo de asistencia necesita?'
    '#options':
      'Setting up my ActiveNet account (the system Portland Parks and Recreation uses for class/recreation registrations)': 'Configuración de mi cuenta de ActiveNet (el sistema que utiliza Portland Parks and Recreation para las inscripciones a clases y actividades recreativas).'
      'Instructions and resources to help me get signed up for upcoming recreation activities': 'Instrucciones y recursos para ayudarme a inscribirme en las próximas actividades recreativas.'
  container_materials:
    '#title': 'Solicitar materiales'
  request_materials_type:
    '#title': '¿Los materiales que solicita...'
    '#options':
      website: 'en el sitio web de la ciudad?'
      event: 'para un evento o actividad específica?'
      printed: 'un documento impreso no disponible en línea?'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor, describa los materiales.'
  request_materials_url:
    '#title': '¿Cuál es la dirección web (URL) de la página donde se encuentran los materiales?'
  request_materials_description:
    '#title': 'Nombre y/o descripción del documento'
  page_you_last_viewed:
    '#title': 'La página que vio por última vez'
  container_report_website_issue:
    continue_button:
      '#template': |-
        <p>
            <a class="button button--primary" href="/feedback?page_you_last_viewed={{ data.page_you_last_viewed }}&subject={{ 'Fix an accessibility issue with a City app or website'|url_encode }}" aria-label="Continuar para reportar un problema de accesibilidad con una aplicación o sitio web de la ciudad">Continuar para reportar un problema de aplicación o sitio web</a>
        </p>
  container_event:
    '#title': 'Detalles del evento'
  request_event_name:
    '#title': 'Nombre de la actividad, evento o programa'
  request_event_date:
    '#title': 'Fecha del evento'
  request_event_location:
    '#title': 'Ubicación del evento'
  request_event_bureau_sponsor:
    '#title': 'anfitrión del evento'
    '#description': '<p>Especifique la oficina, la oficina, el programa, el proyecto o el funcionario electo de la ciudad que organiza el evento, si lo sabe.</p>'
  request_event_url:
    '#title': 'URL de detalles del evento'
    '#description': '<p>Copie y pegue la dirección URL del sitio web del evento, programa o material, si la conoce.</p>'
  container_event_accommodations:
    '#title': 'Alojamiento para eventos'
  request_event_accommodations_type:
    '#title': '¿Qué tipo de alojamiento está solicitando?'
    '#description': '<p>Marque todo lo que corresponda.</p>'
    '#options':
      accessible_parking: 'Estacionamiento accesible'
      accessible_entrance: 'Una entrada accesible al evento y rutas a los baños.'
      communication_aids: 'Ayudas de comunicación'
      accessible_materials: 'Materiales en un formato accesible'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor, describa su solicitud. No incluya información personal ni relacionada con la salud.'
  request_event_communiation_aids_type:
    '#title': '¿Qué tipo de ayudas de comunicación preferiría?'
    '#options':
      captioning: subtítulos
      listening_device: 'Dispositivo de asistencia auditiva'
      interpretation_asl: 'Interpretación en ASL'
      interpretation_other: 'Interpretación en otra lengua de signos o táctil'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor, describa su solicitud. No incluya información personal ni relacionada con la salud.'
  request_event_materials_format:
    '#title': '¿Qué formato de materiales de eventos preferiría?'
    '#options':
      accessble_word_doc: 'Documento electrónico accesible (Microsoft Word)'
      accessible_pdf: 'Documento electrónico accesible (PDF)'
      large_print: 'papel de letra grande'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor, describa su solicitud. No incluya información personal ni relacionada con la salud.'
  container_remove_barrier:
    '#title': 'Eliminar barrera'
  request_barrier_type:
    '#title': '¿Qué tipo de problema estás reportando? ¿Cómo podemos facilitarle el acceso?'
    '#options':
      barrier: 'Barrera: hay una barrera, obstrucción o algo en el camino que impide el acceso'
      parking: 'Estacionamiento: no hay estacionamiento accesible o hay un problema con los lugares existentes'
      signage: 'Señalización: no hay señales o las señales no están claras'
    '#other__option_label': 'Algo más...'
    '#other__description': 'Por favor describa.'
  report_location:
    '#title': 'Ubicación de la barrera o problema'
    '#location_search__title': 'Búsqueda por ubicación'
    '#location_map__title': 'Mapa de localización'
    '#suggestions_modal__title': Sugerencias
    '#status_modal__title': 'Indicador de estado'
    '#location_address__title': 'Dirección o cruce de calles'
    '#location_lat__title': Latitud
    '#location_lon__title': Longitud
    '#place_name__title': 'Ponga su nombre'
    '#location_details__title': 'Detalles de ubicación'
    '#location_asset_id__title': 'ID de activo'
  report_barrier_description:
    '#title': 'Descripción del problema'
    '#description': '<p>Describa el problema en detalle. ¿Cómo podemos facilitar el acceso a tu ciudad? Para proteger su privacidad, no incluya ninguna información personal o relacionada con la salud.</p>'
  container_change_policy:
    '#title': 'Política de cambios'
  report_policy_request:
    '#title': '¿Cuál es su solicitud?'
    '#description': '<p>Describa el cambio de política o procedimiento que está solicitando. Para proteger su privacidad, no incluya ninguna información personal o relacionada con la salud.</p>'
  section_contact:
    '#title': 'Información del contacto'
  contact_name:
    '#title': 'Su nombre'
  contact_email:
    '#title': 'Tu correo electrónico'
    '#description': '<p>Usaremos su correo electrónico para responder a sus comentarios o solicitudes.</p>'
  contact_phone:
    '#title': Teléfono
  contact_phone_assistance_type:
    '#title': 'Si necesita asistencia telefónica, seleccione una opción'
    '#options':
      vri: VRI
      relay: 'Servicio de retransmisión de Oregón (TTY)'
      interpreter: Interprete
      none: 'Ninguna de las anteriores'
  support_agent_use_only:
    '#title__title': ''
  report_ticket_id:
    '#title': 'Informar ID de ticket'
  computed_location_address:
    '#title': 'Dirección de ubicación calculada'
  computed_location_latlon:
    '#title': 'Ubicación calculada latlon'
  actions:
    '#title': 'Botones de envío'
    '#submit__label': Enviar
settings:
  confirmation_title: '¡Gracias por enviar su solicitud!'
  confirmation_message: '<p>Su solicitud ha sido recibida y debe ser contactado dentro de las 48 horas.</p>'
handlers:
  zendesk_new_ticket:
    label: 'Boleto nuevo de Zendesk'
    notes: 'Crea un nuevo boleto de solicitud de alojamiento de ADA y lo asigna al grupo 311.'
