title: 'Reportar Discriminación'
elements: |
  report_discrimination:
    '#title': '¿Le gustaría presentar una queja sobre una política de la Ciudad o una acción tomada por un programa, empleado o contratista de la Ciudad que viole sus derechos y lo discrimine?'
    '#options':
      'Yes': 'Sí, me gustaría denunciar discriminación'
      'No': 'No, pero me gustaría solicitar una adaptación de la ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p>Realice una solicitud a través del servicio de <a href="/311/ada-request">alojamiento ADA</a> de la ciudad. También puede llamarnos al <a href="tel:+1-503-823-4000">503-823-4000</a> o TTY a través del Servicio de retransmisión de Oregon: <a href="tel:711">711</a> . El personal está disponible para ayudar de lunes a viernes de 8 am a 5 pm</p></div>'
  report_how_to_complete:
    '#title': '¿Cómo le gustaría completar su solicitud o informe?'
    '#options':
      'Call us': Llámanos
      'Continue online': 'Continuar en línea'
  confidentiality_waiver:
    '#title': 'Exención de confidencialidad'
    '#description': '<p>Es política de la ciudad mantener confidencial la información que proporcione en este formulario con el fin de cumplir con su solicitud. La ciudad también intentará mantener la confidencialidad de su información en caso de que alguien solicite que se divulgue como registro público en virtud de la <a href="/attorney/oregon-public-records-law" data-renderer-mark="true">Ley de Registros Públicos de Oregón</a>. Si prefiere renunciar a esta confidencialidad, seleccione esa opción a continuación.</p>'
    '#options':
      'I do not waive confidentiality.': '<em>No</em> renuncio a la confidencialidad.'
      'I choose to waive confidentiality.': 'Elijo renunciar a la confidencialidad.'
  report_who:
    '#title': '¿Para quién está haciendo esta solicitud o queja?'
    '#options':
      Myself: 'Para mí'
      'Someone else': 'Alguien más'
      'Neither of these apply to me': 'Ninguna de estas opciones se aplica a mí'
  report_who_neither_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Next Steps</h2><p>Completing this form starts an investigatory and potentially legal process. It is intended to be used by individuals or on behalf of individuals that believe they have been discriminated against.</p><p>If you have a concern or are attempting to point out a condition in the city that may be intentionally or unintentionally leading to the discrimination of a protected class, please use our <a href="/help/contact-elected-official">Contact an elected official form.</a></p></div>'
  report_on_behalf_of_permission:
    '#title': '¿Obtuvo su permiso para presentar esta queja?'
  report_on_behalf_of_name:
    '#title': '¿Cuál es el nombre de las personas o grupos discriminados?'
  report_third_party_relationship:
    '#title': '¿Cuál es su relación con ellos y por qué presenta la queja en nombre de un tercero?'
  report_on_behalf_of_permission_text_stop:
    '#markup': '<h2>Próximos pasos</h2><p>Completando este formulario, usted inicia un proceso de investigación y potencialmente legal. Está destinado para que lo usen personas o grupos que creen que se discriminó directamente en su contra.</p><p>Si tiene una preocupación o intenta señalar una condición en la Ciudad que pueda dar lugar, intencional o no intencionalmente, a la discriminación de una clase protegida, use nuestro Formulario de contacto con un representante electo.</p>'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p>Llámenos al 311, <a href="tel:+15038234000">(503) 823-4000</a> o al <a href="tel:711">711</a> para TTY a través del Servicio de retransmisión de Oregon. El personal está disponible de lunes a viernes de 8:00 am a 5:00 pm, excepto días festivos federales.</p></div>'
  report_discrimination_basis:
    '#title': 'Creo que la discriminación que experimenté se basó en...'
    '#description': '<p>(Marque todo lo que corresponda)</p>'
  report_discrimination_date:
    '#title': '¿Cuándo ocurrió la discriminación?'
  report_location:
    '#location_search__title': '¿Dónde ocurrió el incidente? '
    '#place_name__title': 'Nombre e información del lugar'
    '#location_details__title': 'Dé cualquier otra información que pueda ayudarnos a encontrar el lugar que está reportando, incluyendo si este lugar tiene un nombre, como un edificio público.'
  report_discrimination_bureau_office_etc:
    '#title': 'Proporcione el nombre de la oficina, oficina, empleado, evento o programa de la ciudad asociado con la discriminación.'
  report_discrimination_description:
    '#title': 'En sus propias palabras, describa la supuesta discriminación.'
    '#description': '<p>Por favor explique lo que sucedió; quien estaba involucrado; qué política, programa o actividad fue discriminatoria (si corresponde); por qué cree que sucedió y cómo fue discriminado. Para proteger su privacidad, no incluya ninguna información personal o relacionada con la salud.</p>'
  report_discrimination_witnesses:
    '#title': '¿Hubo testigos de la discriminación?'
  report_discrimination_witnesses_contact_known:
    '#title': '¿Sabe su nombre y número de teléfono o dirección de correo electrónico?'
    '#description': '<p>Solo se contactará a los testigos si es necesario para investigar su reclamo. Si se les contacta, los testigos pueden elegir si quieren participar en el proceso de investigación.</p>'
  report_discrimination_witness_1_name:
    '#title': 'Nombre del primer testigo'
  report_discrimination_witness_1_phone:
    '#title': 'Teléfono del primer testigo'
  report_discrimination_witness_1_email:
    '#title': 'Correo electrónico del primer testigo'
  report_discrimination_add_witness:
    '#title': '¿Agregar otro testigo?'
    '#options':
      'Add another witness': 'Agregar otro testigo'
  report_discrimination_witness_2_name:
    '#title': 'Nombre del segundo testigo'
  report_discrimination_witness_2_phone:
    '#title': 'Teléfono del segundo testigo'
  report_discrimination_witness_2_email:
    '#title': 'Correo electrónico del segundo testigo'
  report_discrimination_file_upload:
    '#title': 'Si corresponde, adjunte fotos u otros materiales relevantes para su queja.'
  report_discrimination_desired_outcome:
    '#title': '¿Qué tipo de acción o resolución le gustaría ver tomada?'
  report_discrimination_filed_complaint_other:
    '#title': '¿Ha presentado una queja ante otras agencias federales, estatales o locales, o dentro de algún tribunal federal o estatal?'
    '#description': '<p>Tiene derecho a presentar una solicitud ante cualquier agencia o tribunal. Presentar una queja ante otra agencia o tribunal no le impide presentar una queja ante la Ciudad de Portland. En ciertas situaciones, las agencias se coordinarán para asegurarse de que la agencia o el tribunal correspondiente investigue la denuncia.</p>'
    '#options':
      'Yes': Sí
      'Prefer not to answer': 'Prefiero no responder'
  report_discrimination_filed_complaint_other_agency:
    '#title': '¿Qué agencia o tribunal?'
  report_agency_contact_markup:
    '#markup': '<p>Si presentó la queja ante otra agencia o tribunal, dé el nombre y teléfono o dirección de correo electrónico de cualquier contacto o representante que recibió la queja, si lo tiene.</p>'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Persona de contacto de la agencia o del tribunal'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Teléfono de contacto de la agencia o tribunal'
  report_legal_representative_name:
    '#title': 'Dé el nombre de contacto de su representación legal, si la tiene.'
  report_legal_representative_contact_number:
    '#title': 'La información de contacto de su representación legal, si la tiene.'
  contact_name:
    '#title': 'Su nombre'
  contact_email:
    '#title': 'Correo electrónico'
    '#description': '<p>Usaremos su correo electrónico para confirmar su envío.</p>'
  contact_phone:
    '#title': Teléfono
  contact_preferred_method:
    '#title': 'Si es necesario, ¿preferiría que nos comuniquemos con usted por teléfono o correo electrónico?'
    '#options':
      Phone: Teléfono
      Email: 'Correo electrónico'
  contact_interpreter:
    '#title': '¿Necesitas un intérprete?'
    '#options':
      'Yes, VRI (Video Remote Interpretation)': 'Sí, VRI (Video Interpretación Remota)'
      'Yes, Oregon Relay Service': 'Sí, servicio de retransmisión de Oregón'
      'Yes, language interpreter': 'Sí, intérprete de idiomas.'
  contact_language:
    '#title': '¿Cual idioma?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Acuse de recibo del denunciante</strong></p><p>Al enviar este formulario, afirmo que (1) he leído, entiendo y acepto los <a href="/code/23">términos de los procedimientos para rastrear e investigar quejas de derechos civiles</a> y (2) la información que proporcioné en este formulario es verdadera según mi leal saber y entender.</p>'
  complainant_acknowledgement_agree:
    '#title': 'Estoy de acuerdo'
  actions:
    '#title': 'Botones de envío'
    '#submit__label': Enviar
  report_ticket_id:
    '#title': 'Informar ID de ticket'
settings:
  confirmation_title: ''
  confirmation_message: ''
handlers:
  zendesk_new_ticket:
    label: 'Boleto nuevo de Zendesk'
    notes: 'Crea un nuevo ticket de queja por Discriminación y lo asigna al grupo 311: ADA y Discriminación.'
