title: 'Comentarios del sitio web'
description: '<p>Este formulario web se utiliza para recopilar comentarios sobre el sitio web de usuarios y editores.</p>'
elements: |
  subject:
    '#title': 'Tipo de retroalimentación'
    '#options':
      "I cannot find what I'm looking for": 'No puedo encontrar lo que busco'
      'I have a question': 'Tengo una pregunta'
      'The page looks broken': 'La página se ve rota'
      'The information looks incorrect': 'La información parece incorrecta'
      'Contact an elected official with feedback': 'Póngase en contacto con un funcionario electo con comentarios'
      'Fix an accessibility issue with a City app or website': 'Solucionar un problema de accesibilidad en una aplicación o sitio web de la ciudad'
    '#empty_option': '-- Seleccionar --'
  link_to_contact_elected:
    '#markup': '<div class="alert alert--info next-steps"><h2>Próximos pasos</h2><p>Utilice el <a href="/help/contact-elected-official">formulario Comuníquese con un funcionario electo</a> para enviar sus comentarios o solicitar una reunión.</p></div>'
  feedback:
    '#title': Detalles
    '#description': '<p>Sea específico, para que podamos ayudarlo mejor.</p>'
  your_name:
    '#title': 'Su nombre'
  email_address:
    '#title': 'Tu correo electrónico'
  page_you_last_viewed:
    '#title': 'Página que vio por última vez'
    '#description': '<p>Puede cambiar esta dirección si prefiere comentar en una página diferente.</p>'
    '#default_value': '[server:HTTP_REFERER]'
  public_records_statement:
    '#markup': '<p>La información que proporciona en este formulario se considera un registro público según la <a href="/attorney/oregon-public-records-law" data-renderer-mark="true">Ley de Registros Públicos de Oregón</a> y está disponible para el público a pedido.</p>'
  actions:
    '#title': 'Botones de envío'
  ip_address:
    '#title': 'Dirección IP'
settings:
  form_close_message: '<p>Nuestro formulario de comentarios está cerrado temporalmente. Si tiene comentarios o sugerencias sobre cómo podemos mejorar esta página, envíe un correo electrónico al equipo web a powr@portlandoregon.gov.</p>'
  confirmation_message: '<h2>¡Gracias por enviarnos sus comentarios, apreciamos su ayuda!</h2><p>Deberías recibir una confirmación por correo electrónico en un momento. Puede responder a ese correo electrónico para agregar información adicional o comentarios a sus comentarios.<br><br>Nombre: [webform_submission:valores:tu_nombre]<br><br>Correo electrónico: [webform_submission: valores: dirección de correo electrónico]<br><br>Tipo de comentario: [webform_submission:valores:asunto]<br><br>Última página vista: <a href="[webform_submission:values:page_you_last_viewed]">[webform_submission:values:page_you_last_viewed]</a><br><br>Comentarios: [webform_submission:values:feedback]</p>'
handlers:
  submit_report_to_311:
    label: 'Enviar informe al 311'
    notes: ''
    settings:
      from_name: ''
      subject: '[webform_submission:valores:asunto:sin procesar] - [webform_submission:valores:retroalimentación]'
      body: '<p>Asunto: [webform_submission:valores:asunto]</p><p>Comentarios: [webform_submission:values:feedback]</p><p>Nombre: [webform_submission:valores:tu_nombre]</p><p>Correo electrónico: [webform_submission: valores: dirección de correo electrónico]</p><p>Página vista por última vez: [webform_submission:values:page_you_last_viewed]</p><p>Enviado el: [webform_submission:created]</p><p>Agente de usuario: [servidor:HTTP_USER_AGENT]</p><p>[webform_submission:valores:agent_summary]</p>'
  submit_report_to_website_support:
    label: 'Enviar informe al soporte del sitio web'
    notes: ''
    settings:
      from_name: ''
      subject: '[webform_submission:valores:asunto:sin procesar] - [webform_submission:valores:retroalimentación]'
      body: '<p>Asunto: [webform_submission:valores:asunto]</p><p>Comentarios: [webform_submission:values:feedback]</p><p>Nombre: [webform_submission:valores:tu_nombre]</p><p>Correo electrónico: [webform_submission: valores: dirección de correo electrónico]</p><p>Página vista por última vez: [webform_submission:values:page_you_last_viewed]</p><p>Enviado el: [webform_submission:created]</p><p>Agente de usuario: [servidor:HTTP_USER_AGENT]<br><br>[webform_submission:valores:agent_summary]</p>'
