elements: |
  report_confirm_non_emergency:
    '#title': 'Ma arrin degdeg ah oo nafta halis gelinaysa baa taas oo qof uu dhaawacmay ama uu dab holcaayo ka jiro?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Fadlan jooji buuxinta foomkaan oo wac 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Fadlan samee xulasho si aad u sii wadato.</strong></p>'
  markup:
    '#markup': '<p><em><strong>Xilliyada mashquulka badan ee sanadka, hay''adaha fulinta sharciga ma haystaan awood ay kaga jawaabaan dhammaan wicitaannada aan degdegga ahayn. Baarayaasha Dabka ayaa baaraya dhammaan dabka la xiriira rashka, dadka ku xad-gudbay amarka ayaana masuul ka noqon doona.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Fadlan la wadaag goobtaada markaad maqlayso bululeedka'
    '#location_address__description': 'Tusaale ahaan, cinwaanka gurigaaga'
    '#unit_number__title': 'Lambarka Guriga'
    '#location_city__title': 'Magaalada'
    '#location_state__title': 'Gobolka'
    '#location_zip__title': 'Koodhka Boostada'
  report_confirm_known_location:
    '#title': 'Ma taqaanaa goobta laga shidaayo bululeedka?'
  report_incident_location:
    '#title': 'Goobta Dhacdada'
  report_location:
    '#title': 'Goobta Dhacdada'
    '#location_search__title': 'Raadinta Goobta'
    '#location_search__description': 'Ka raadi khariidadda ciwaan, waddooyin isgoys, jardiino, ama xarun bulsho. Ama isticmaal khariidada si aad u gujiso goob.'
    '#location_details__title': 'Faahfaahinta Goobta'
    '#location_details__description': 'Fadlan bixi faahfaahin kasta oo kale oo naga caawin karta helitaanka goobta aad ka warbixinayso.'
  report_date:
    '#title': 'Taariikhda Dhacdada'
  report_time:
    '#title': 'Qiyaasta Waqtiga Dhacdada'
  report_incident_description:
    '#title': 'Bixi sharraxaad waxtar leh oo ku saabsan dhacdada'
    '#description': '<p>Tusaale ahaan: midabka guriga, mulkiilaha, baabuurta la xiriira, haddii aad hayso muuqaal ama xogta duuwan ee dhacdada. Haddii loo baahdo, qof ayaa kula soo xiriiri doona si uu kuu siiyo tilmaamo ku saabsan sida loo soo gudbiyo sawirrada ama fiidiyowyada.</p>'
  section_contact:
    '#title': 'Macluumaadkaaga Xiriirka'
    '#description': '<p>Fadlan ogoow: Maadaama ay jiraan kheyraad xaddidan, waa INAADAN filan jawaab aad ka hesho warbixintan.</p>'
  contact_name:
    '#title': 'Magaca'
  contact_email:
    '#title': 'Iimaylka'
    '#description': '<p>Waxaan u isticmaali doonnaa iimaylkaaga si aan u xaqiijinno soo gudbintaada.</p>'
  contact_phone:
    '#title': 'Telefanka'
  section_confidentiality:
    '#title': 'Sirta'
  confidentiality_waiver:
    '#title': 'Ka Tanaasulidda Qarsoodiga'
    '#description': '<p>Xeerka Magaaladu waa in macluumaadka aad ku bixiso foomkaan la qariyo si loo fuliyo codsigaaga. Magaaladu waxay sidoo kale isku dayi doontaa inay macluumaadkaaga sir ka dhigto haddii qof uu codsado in loo sii daayo diiwaan dadweyne sida ku cad <a href="/attorney/oregon-public-records-law">Sharciga Diiwaanada Dadweynaha Oregon</a>. Haddii aad doorbidayso inaad ka tanaasusho sirtaan, fadlan dooro ikhtiyaarkaas hoose.</p>'
    '#options':
      'I do not waive confidentiality': '<em>Kama</em> tanaasulaayo sirta.'
      'I waive confidentiality': 'Waxaan doortay inaan ka tanaasulo sirta.'
settings:
  confirmation_title: 'Waad ku mahadsan tahay soo gudbinta cabasho!'
  confirmation_message: '<p>Warbixintaada (#[webform_submission:values:report_ticket_id]) waa la helay.</p><p>Inta lagu jiro wakhtiyada tirada badan ee sanadka, Booliisku ma lahan awood ay kaga jawaabaan dhammaan wicitaanada aan degdega ahayn. Iyadoo agabka aan la heli karin si looga jawaabo cabashooyinka badankooda ee ku saabsan bululeedka, waxaan u uruurineynaa macluumaadka dadaalka socda si loo gaaro u hoggaansanaanta Mamnuucida Bululeedka. Waa INAADAN filan in dib laguugu soo celiyo wicitaanka kadib warbixintaan.</p><p>Baarayaasha Dabka ayaa baaraya dhammaan dabka la xiriira bululeedka, dadka ku xad-gudbay amarka ayaana masuul ka noqon doona.</p><p>Haddii xaaladda bululeedka ay ku lug leedahay qof la dhaawacay ama haddii shay dab qabsado, wac 911.</p>'
handlers:
  email:
    settings:
      body: '<h2>Waad ku mahadsan tahay soo gudbinta cabasho!</h2><p>Warbixintaada (#[webform_submission:values:report_ticket_id]) waa la helay.</p><p>Inta lagu jiro wakhtiyada tirada badan ee sanadka, Booliisku ma lahan awood ay kaga jawaabaan dhammaan wicitaanada aan degdega ahayn. Iyadoo agabka aan la heli karin si looga jawaabo cabashooyinka badankooda ee ku saabsan bululeedka, waxaan u uruurineynaa macluumaadka dadaalka socda si loo gaaro u hoggaansanaanta Mamnuucida Bululeedka. Waa INAADAN filan in dib laguugu soo celiyo wicitaanka kadib warbixintaan.</p><p>Baarayaasha Dabka ayaa baaraya dhammaan dabka la xiriira bululeedka, dadka ku xad-gudbay amarka ayaana masuul ka noqon doona.</p><p>Haddii xaaladda bululeedka ay ku lug leedahay qof la dhaawacay ama haddii shay dab qabsado, wac 911.</p>'
