display:
  default:
    display_title: デフォルト
    display_options:
      fields:
        file_name:
          label: 名前
        asset_type:
          label: タイプ
      pager:
        options:
          tags:
            next: '次 ›'
            previous: '‹ 前'
            first: '« 最初'
            last: '最後 »'
          expose:
            items_per_page_label: ページ毎の件数
            items_per_page_options_all_label: '- 全て -'
            offset_label: オフセット
