display:
  default:
    display_title: デフォルト
    display_options:
      fields:
        usage_field:
          label: セクション
      pager:
        options:
          tags:
            next: '次 ›'
            previous: '‹ 前'
            first: '« 最初'
            last: '最後 »'
      arguments:
        asset_id:
          exception:
            title: すべて
