display:
  default:
    display_title: デフォルト
    display_options:
      fields:
        file_name:
          label: 名前
        asset_type:
          label: タイプ
        status_badge:
          label: 状態
        warnings:
          admin_label: 警告
          label: 警告
        operations:
          admin_label: 操作
          label: 操作
      pager:
        options:
          tags:
            next: '次 ›'
            previous: '‹ 前'
            first: '« 最初'
            last: '最後 »'
          expose:
            items_per_page_label: ページ毎の件数
            items_per_page_options_all_label: '- 全て -'
            offset_label: オフセット
      exposed_form:
        options:
          submit_button: 適用
          reset_button_label: リセット
          exposed_sorts_label: 並び替え基準
          sort_asc_label: 昇順
          sort_desc_label: 降順
          text_input_required: フィルターを選択して適用をクリックし、結果を表示
          bef:
            general:
              secondary_label: 高度なオプション
      filters:
        status:
          expose:
            label: 状態
          group_info:
            label: 状態
            group_items:
              1:
                title: 待機
        archive_reason:
          group_info:
            group_items:
              1:
                title: 参照
              4:
                title: その他
