display:
  default:
    display_title: デフォルト
    display_options:
      fields:
        source_entity_id:
          label: エンティティID
        field_name:
          label: フィールド名
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: ページ毎の件数
            items_per_page_options_all_label: '- 全て -'
            offset_label: オフセット
      arguments:
        asset_id:
          exception:
            title: すべて
