<?php

use Drupal\redirect\Entity\Redirect;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function portland_legacy_redirects_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle)
{
  _add_field_legacy_path_validation_constraint_path_exists($fields, $entity_type, $bundle);
}

/**
 * Add relative_path constraint to field_legacy_path if it exists in fields array for the given bundle.
 * Called by hook_entity_bundle_field_info_alter.
 */
function _add_field_legacy_path_validation_constraint_path_exists(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if (array_key_exists('field_redirects', $fields)) {
    $fields['field_redirects']->addConstraint('relative_path', []);
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function portland_legacy_redirects_entity_base_field_info($entity_type) {
  if ($entity_type->id() === 'node' || $entity_type->id() === 'group') {
    $fields = [];

    // add a field that allows the page's redirects (labeled as Legacy Paths) to be modified
    // outside the redirects UI.
    $fields['field_redirects'] = BaseFieldDefinition::create('string')
      ->setName('field_redirects')
      ->setLabel(t('Legacy Path'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\portland_legacy_redirects\Field\RedirectList')
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'text_textfield',
        'weight' => 50,
      ])
      ->setDescription(t('This field is used to create redirects to this page from legacy pages in the old site. Multiple paths may be entered in case several pages have been combined during migration. Once these paths are created, they may only be modified or removed by an administrator. Paths must be relative and start with a slash. For example, the page "https://www.portlandoregon.gov/bts/39479" should be entered as "/bts/39479."'))
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED);

    return $fields;
  }
}

/**
 * Strips leading slash from a path.
 */
function _portland_legacy_redirects_utility_strip_leading_slash($path) {
  return substr($path, 0, 1) == "/" ? substr($path, 1) : $path;
}

