<?php

use Drupal\group\GroupMembershipLoaderInterface;
use Drupal\group\Entity\GroupInterface;
use Drupal\group\Entity\GroupTypeInterface;
use Drupal\group\Entity\GroupContentTypeInterface;
use Drupal\pathauto\Form\PathautoBulkUpdateForm;

const GROUP_CONTENT_TYPES = array('services', 'locations', 'buildings', 'news');

/**
 * Implements hook_ENTITY_TYPE_create().
 */
// When a content type is installed to a group type, create the alias for all groups with that group type.
function portland_group_content_type_create(GroupContentTypeInterface $groupContentType) {
    // Get all groups of this type
    $properties = ['type' => $groupContentType->getGroupTypeId()];
    $grps = \Drupal::entityTypeManager()
        ->getStorage('group')
        ->loadByProperties($properties);
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    // content_plugin:"group_node:news"
    $contentTypePlugin = $groupContentType->getContentPluginId();
    if(strpos($contentTypePlugin, 'group_node:') !== 0) return;
    $contentType = substr($contentTypePlugin, strlen('group_node:'));

    // For each group, generate a new URL alias "group.field_shortname_or_acronym/contents"
    foreach ($grps as $grp) {
        $shortname = \Drupal::service("pathauto.alias_cleaner")
            ->cleanString($grp->get('field_shortname_or_acronym')->value);
        $alias = "/$shortname/$contentType";
        $gid = $grp->id();
        $system_path = "/group/$gid/$contentType";
        $path = \Drupal::service('path.alias_storage')->save($system_path, $alias, $lang);
    }    
}
/**
 * Implements hook_ENTITY_TYPE_delete().
 */
// When a content type is uninstaled from a group type, delete the alias added during creation time.
function portland_group_content_type_delete(GroupContentTypeInterface $groupContentType) {
    // Get all groups of this type
    $properties = ['type' => $groupContentType->getGroupTypeId()];
    $grps = \Drupal::entityTypeManager()
        ->getStorage('group')
        ->loadByProperties($properties);
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    // content_plugin:"group_node:news"
    $contentTypePlugin = $groupContentType->getContentPluginId();
    if(strpos($contentTypePlugin, 'group_node:') !== 0) return;
    $contentType = substr($contentTypePlugin, strlen('group_node:'));

    // For each group, delete the URL alias "/group.field_shortname_or_acronym/contents". E.g. "/bds/news"
    foreach ($grps as $grp) {
        $shortname = \Drupal::service("pathauto.alias_cleaner")
            ->cleanString($grp->get('field_shortname_or_acronym')->value);
        $alias = "/$shortname/$contentType";
        $gid = $grp->id();
        $system_path = "/group/$gid/$contentType";

        // If found an alias, delete it.
        $existing_alias = \Drupal::service('path.alias_storage')
            ->lookupPathAlias($system_path, $lang);
        if($existing_alias) {
            $path = \Drupal::service('path.alias_storage')
                ->delete(['alias' => $existing_alias, 'langcode' => $lang]);
        }
    }  
}


/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function portland_group_insert(GroupInterface $group) {

    $gid = $group->id();
    $shortname = \Drupal::service("pathauto.alias_cleaner")->cleanString($group->get('field_shortname_or_acronym')->value);

    // POWR-142
    // 1.2. Generate URL aliases for content type subpages using group shortname (ie. /bds/services)
    foreach (GROUP_CONTENT_TYPES as $type) {
        $system = "/group/$gid/$type";
        $alias = "/$shortname/$type";
        // save new path alias
        $path = \Drupal::service('path.alias_storage')->save($system, $alias, "en");
    }

    // Workaround for Drupal bug: https://www.drupal.org/project/inline_entity_form/issues/2966933
    $group->path->pathauto = Drupal\pathauto\PathautoState::CREATE;

    // <TODO:>LOW PRIORITY: Generate URL aliases for group action links using group shortname (ie. /bds/content, /bds/members)</TODO:>
}
  
/**
 * Implements hook_ENTITY_TYPE_update().
 */
function portland_group_update(GroupInterface $group) {

    // 4.2. Bulk regenerate URL aliases for content by running pathauto batch processing
    $batch = array(
        'title' => t('Bulk updating URL aliases'),
        'operations' => array(
          array('Drupal\pathauto\Form\PathautoBulkUpdateForm::batchStart', array()),
        ),
        'finished' => 'Drupal\pathauto\Form\PathautoBulkUpdateForm::batchFinished',
    );
    $batch['operations'][] = array('Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess', ["canonical_entities:node", "update"]);
    $batch['operations'][] = array('Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess', ["canonical_entities:group", "update"]);
    $batch['operations'][] = array('Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess', ["canonical_entities:group_content", "update"]);
    batch_set($batch);

    // get goup shortname and build paths
    $gid = $group->id();
    $shortname = substr(str_replace(" ","_",trim(strtolower($group->get('field_shortname_or_acronym')->value))),0,60);
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();

    // TODO: manually regenerate URL alias for main group page; pathauto bulk update isn't getting it sometimes
    $existing_alias = \Drupal::service('path.alias_storage')->lookupPathAlias("/group/$gid", $lang);
    $alias = "/$shortname";
    // if it exists and doesn't match current alias, delete and re-save
    if ($existing_alias && $existing_alias != $alias) {
        \Drupal::service('path.alias_storage')->delete(['alias' => $existing_alias, 'langcode' => $lang]);
        $path = \Drupal::service('path.alias_storage')->save("/group/$gid", $alias, $lang);
    }
    
    // POWR-142: Regenerate URL aliases for content type subpages using group shortname (ie. /bds/services)
    // reference: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Path%21AliasStorage.php/class/AliasStorage/8.6.x
    foreach (GROUP_CONTENT_TYPES as $type) {
        $system_path = "/group/$gid/$type";
        $alias = "/$shortname/$type";

        $existing_alias = \Drupal::service('path.alias_storage')->lookupPathAlias($system_path, $lang);

        // if it already exists and matches, do nothing
        if ($existing_alias && $existing_alias == $alias) continue;

        // if it exists and doesn't match current alias, delete in preparation for re-save
        if ($existing_alias && $existing_alias != $alias) {
            \Drupal::service('path.alias_storage')->delete(['alias' => $existing_alias, 'langcode' => $lang]);
        }

        // save new or updated alias
        $path = \Drupal::service('path.alias_storage')->save($system_path, $alias, $lang);
    }

    // <TODO:>LOW PRIORITY: rEGenerate URL aliases for group action links using group shortname (ie. /bds/content, /bds/members)</TODO:>
}