<?php

use Drupal\group\Entity\GroupInterface;


/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function portland_group_insert(GroupInterface $group) {

    echo "HALT portland_group_insert";
    exit();

}
  
/**
 * Implements hook_ENTITY_TYPE_update().
 */
function portland_group_update(GroupInterface $group) {

    // TODO: if field field_shortname_or_acronym has changed, we need to update all the URL aliases
    //       for content under this group 
    
    echo "HALT portland_group_update";
    exit();

}