<?php

/**
 * Implements hook_theme().
 */
function openapi_swagger_ui_theme() {
  return [
    'swagger_ui' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function openapi_swagger_ui_menu_links_discovered_alter(&$links) {
  // Disable menu items depending on module enabled.
  // @todo Is this possible to do in custom menu class?
  //   Currently this is not working.
  $module_handler = \Drupal::moduleHandler();
  if (!$module_handler->moduleExists('jsonapi')) {
    unset($links['openapi_swagger_ui.jsonapi']);
  }
  if (!$module_handler->moduleExists('rest')) {
    unset($links['openapi_swagger_ui.rest.list']);
  }
}
